"""Regenerates the "4 player relocations" block of us.toml from relocate.py."""
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOML = os.path.join(HERE, '..', '..', 'us.toml')
BEGIN = '# BEGIN 4 player relocations (generated by tools/players4/relocate.py, do not edit by hand)\n'
END = '# END 4 player relocations\n'

block = subprocess.run([sys.executable, os.path.join(HERE, 'relocate.py'), 'toml'], capture_output=True, text=True,
                       check=True).stdout
text = open(TOML, encoding='utf-8', newline='').read()
nl = '\r\n' if '\r\n' in text else '\n'
block = block.replace('\r\n', '\n').replace('\n', nl)
begin, end = BEGIN.replace('\n', nl), END.replace('\n', nl)
if begin in text:
    a = text.index(begin)
    b = text.index(end, a) + len(end)
    text = text[:a] + begin + block + end + text[b:]
else:
    text = text.rstrip(nl) + nl + nl + begin + block + end
open(TOML, 'w', encoding='utf-8', newline='').write(text)
print('us.toml updated')
