"""Pairs Rush 2049's N64 sound effect ids with the Dreamcast disc's, and lists the disc's sound banks.

    dc_sounds.py [--banks] [--emit src/rush2049dc/rush2049_dc_sounds.inc]

The N64 plays MusyX effects 0x00-0x76; the disc plays samples out of .KAT banks by a global id 0x000-0x136 (bank
table 0x8C0A7904: {name[0x14], u32 first id, u32 last id, u32 loaded, ...} x 9). Pairs come from tables both versions
have with sounds in the same places (the type table's start/loop/stop sounds by type name, the engine layers by
position, the battle weapons by weapon) and, for the ids the port plays from its own code, from the call sites the
two executables share (MANUAL below, each with where it was read). --emit writes the map the Dreamcast audio uses.
Needs RUSH2049_ROM (roms.py) and the disc's files (tmp/dc/files from dc_cdi.py all). See
docs/rush2049_research/dreamcast.md.
"""
import os, struct, sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(__file__))
from dc_tables import Exe, n64_segments, n32, nstr, MAIN, BATTLE, DC_BASE

FILES = os.path.join(os.path.dirname(__file__), '..', '..', 'tmp', 'dc', 'files')
BANKS = 0x8C0A7904

# N64 id -> disc id read from matching call sites (N64 function, disc function).
MANUAL = {
    # Explosions: N64 func_800AF06C plays 0x2D at size >= 1, 0x45 from 0.5, else 0x2F; the disc's (0x8C062D40) 0x09,
    # 0x3D, 0x3E (0x45 and 0x2F also pair through the type table: WPR_MINE and RAT).
    0x2D: 0x09,
}
# The N64's per-track songs (main 0x8010FFD4, s32 per 2049 track id 0-18) and the disc's (0x8C0BA76C).
N64_TRACK_SONGS = 0x8010FFD4
DC_TRACK_SONGS = 0x8C0BA76C


def banks(exe):
    out = []
    for i in range(9):
        a = BANKS + i * 0x24
        name = exe.s(a)
        out.append((name, exe.w(a + 0x14), exe.w(a + 0x18)))
    return out


def kat_entries(path):
    d = open(path, 'rb').read()
    n = struct.unpack_from('<I', d, 0)[0]
    out = []
    for i in range(n):
        e = struct.unpack_from('<11I', d, 4 + i * 0x2C)
        out.append(e)
    return out


def table_pairs(exe, seg):
    pairs = defaultdict(set)   # n64 id -> {(dc id, where)}
    # Type table: N64 0x80117530 (122 x 0x30), disc 0x8C0BFD80 (x 0x34), by name; sounds at +0x1C/+0x20/+0x24.
    dc_rows = {}
    j = 0
    while True:
        a = 0x8C0BFD80 + j * 0x34
        try:
            name = exe.s(exe.w(a))
        except (ValueError, struct.error):
            break
        if not name or not name.isprintable():
            break
        dc_rows.setdefault(name, a)
        j += 1
    for k in range(122):
        a = 0x80117530 + k * 0x30
        name = nstr(seg, MAIN, n32(seg, MAIN, a))
        d = dc_rows.get(name)
        if d is None:
            continue
        for off in (0x1C, 0x20, 0x24):
            n, c = struct.unpack('>i', struct.pack('>I', n32(seg, MAIN, a + off)))[0], struct.unpack('<i', struct.pack('<I', exe.w(d + off)))[0]
            if n >= 0 or c >= 0:
                pairs[n].add((c, 'type %s +%X' % (name, off)))
    # Engine layers: N64 0x8010FD80 (0x20 bytes), disc 0x8C0B92A0 (0x1C), sound first.
    for i in range(18):
        n = struct.unpack('>i', struct.pack('>I', n32(seg, MAIN, 0x8010FD80 + i * 0x20)))[0]
        c = struct.unpack('<i', struct.pack('<I', exe.w(0x8C0B92A0 + i * 0x1C)))[0]
        if n >= 0 or c >= 0:
            pairs[n].add((c, 'engine %d.%d' % (i // 2, i % 2)))
    # Battle weapon sounds: N64 battle overlay 0x803942C0, disc 0x8C0D1D7C, s32 per weapon (9), both followed by -1, -1.
    for i in range(9):
        n = n32(seg, BATTLE, 0x803942C0 + i * 4)
        c = exe.w(0x8C0D1D7C + i * 4)
        pairs[n].add((c, 'weapon %d' % i))
    for n, c in MANUAL.items():
        pairs[n].add((c, 'call site'))
    return pairs


def resolve(pairs):
    """{n64: dc}; a disc row without a sound (-1) doesn't count against one with it."""
    out, bad = {}, []
    for n, dcs in pairs.items():
        ids = sorted({c for c, _ in dcs if c >= 0})
        if n < 0 or not ids:
            continue
        if len(ids) > 1:
            bad.append(n)
        out[n] = ids[0]
    return out, bad


def emit(path, mapping, n64_songs):
    with open(path, 'w', newline='\n') as f:
        f.write('// Generated by tools/rush2049/dc_sounds.py from the N64 ROM and the disc; do not edit.\n')
        for mac in ('SOUND', 'N64_TRACK_SONG'):
            f.write('#ifndef %s\n#define %s(...)\n#endif\n' % (mac, mac))
        f.write('// SOUND(N64 sound effect id, disc sound id)\n')
        for n, c in sorted(mapping.items()):
            f.write('SOUND(0x%02X, 0x%03X)\n' % (n, c))
        f.write('// N64_TRACK_SONG(2049 track id, N64 song): main 0x8010FFD4\n')
        for t, s in enumerate(n64_songs):
            f.write('N64_TRACK_SONG(%d, %d)\n' % (t, s))
        for mac in ('SOUND', 'N64_TRACK_SONG'):
            f.write('#undef %s\n' % mac)


def main():
    exe = Exe()
    if '--banks' in sys.argv:
        for name, first, last in banks(exe):
            path = os.path.join(FILES, name.upper())
            ents = kat_entries(path) if os.path.exists(path) else []
            print('%-16s ids %#05x-%#05x (%d), file entries %d' % (name, first, last, last - first + 1, len(ents)))
            for i, e in enumerate(ents):
                print('   %#05x: type %d off %#x size %#x rate %d loop %d fmt %d %d loop %#x-%#x %d %d' %
                      ((first + i,) + e))
    seg = n64_segments()
    pairs = table_pairs(exe, seg)
    mapping, bad = resolve(pairs)
    for n in sorted(pairs):
        dcs = sorted(pairs[n])
        print('N64 %#04x -> disc %s%s' % (n, '%#05x' % mapping[n] if n in mapping else 'none',
                                          '   CONFLICT' if n in bad else ''), '  (%s)' % '; '.join(w for _, w in dcs[:4]))
    n64_songs = [struct.unpack('>i', struct.pack('>I', n32(seg, MAIN, N64_TRACK_SONGS + t * 4)))[0] for t in range(19)]
    dc_songs = [struct.unpack('<i', struct.pack('<I', exe.w(DC_TRACK_SONGS + t * 4)))[0] for t in range(19)]
    print('track songs (2049 track id: N64 song -> disc song):', ', '.join('%d: %d -> %d' % (t, a, b) for t, (a, b) in enumerate(zip(n64_songs, dc_songs))))
    if bad:
        print('conflicts:', ', '.join('%#04x' % n for n in bad))
        sys.exit(1)
    if '--emit' in sys.argv:
        emit(sys.argv[sys.argv.index('--emit') + 1], mapping, n64_songs)


if __name__ == '__main__':
    main()
