"""Builds the track select banners of the SF Rush and Rush 2049 tracks from 128x32 PNGs:
tools/rush1/banners/trackN_<name>.png (SF Rush track 1-7, src/track1_convert.cpp build_logo) and
tools/rush2049/banners/trackN_<name>.png (Rush 2049 race track 1-6, src/track2049_art.cpp build_logo). A track without
a PNG gets its name drawn in its game's banner style with the banner font (tools/banner_font.py); the names come from
track_names in include/track1.h and include/track2049.h.

Each banner becomes the format of Rush 2's track logos: 128x32 CI8 texels in rows top-down (build_logo flips them to
the bottom-up order the game stores) and a 256-entry RGBA5551 palette whose entry 0 is transparent. Pixels with alpha
below 128 are transparent; the rest are reduced to 5 bits a channel and quantized to the 255 remaining entries. The
game draws the banner with its exact colors instead (the full-color image, also in the header, replaces the CI8 one
in the renderer: rush2::upscale::add_exact_image), so the quantizing only shows if that replacement is missing.

  python tools/build_banners.py [--preview DIR]     (--preview also saves every banner as DIR/<game>_trackN.png)

Writes include/track1_banners.h and include/track2049_banners.h.
"""

import os
import re
import sys

from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import banner_font  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
W, H = 128, 32

# (source folder, header, C++ namespace, track count, header with track_names, banner font style).
GAMES = [
    ("tools/rush1/banners", "include/track1_banners.h", "rush2::track1::banners", 7, "include/track1.h", "sfrush"),
    ("tools/rush2049/banners", "include/track2049_banners.h", "rush2::track2049::banners", 6, "include/track2049.h",
     "rush2049"),
]


def track_names(header):
    text = open(os.path.join(ROOT, header)).read()
    m = re.search(r"track_names\[track_count\]\s*=\s*\{([^}]*)\}", text)
    return re.findall(r'"([^"]*)"', m.group(1))


def convert(im):
    """(CI8 texels, RGBA5551 palette, exact RGBA pixels as 0xRRGGBBAA), all top-down."""
    im = im.convert("RGBA")
    if im.size != (W, H):
        raise SystemExit(f"banner is {im.size}, expected {W}x{H}")
    px = list(im.getdata())
    exact = [(r << 24) | (g << 16) | (b << 8) | 255 if a >= 128 else 0 for (r, g, b, a) in px]
    opaque = [a >= 128 for (_, _, _, a) in px]
    rgb = Image.new("RGB", (W, H))
    rgb.putdata([((r >> 3) << 3, (g >> 3) << 3, (b >> 3) << 3) for (r, g, b, _) in px])
    q = rgb.quantize(colors=255, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    pal = q.getpalette()[: 255 * 3]
    idx = list(q.getdata())
    texels = [i + 1 if o else 0 for i, o in zip(idx, opaque)]
    palette = [0] * 256
    for i in range(len(pal) // 3):
        r, g, b = pal[i * 3 : i * 3 + 3]
        palette[i + 1] = ((r >> 3) << 11) | ((g >> 3) << 6) | ((b >> 3) << 1) | 1
    return texels, palette, exact


def build(src, header, namespace, tracks, names_header, style, preview):
    src_dir = os.path.join(ROOT, src)
    images = {}
    for name in sorted(os.listdir(src_dir)):
        m = re.fullmatch(r"track(\d)_\w+\.png", name)
        if m and 1 <= int(m.group(1)) <= tracks:
            images[int(m.group(1))] = Image.open(os.path.join(src_dir, name))
    names = track_names(names_header)
    for t in range(1, tracks + 1):
        if t not in images:
            images[t] = banner_font.render(names[t - 1], style, (W, H))
    banners = {}
    for t, im in sorted(images.items()):
        banners[t] = convert(im)
        if preview:
            os.makedirs(preview, exist_ok=True)
            im.convert("RGBA").save(os.path.join(preview, f"{style}_track{t}.png"))

    out = [
        f"// Generated by tools/build_banners.py from {src}/*.png. Do not edit.",
        "// Track select banners: 128x32 CI8 texels (rows top-down) and RGBA5551 palettes, entry 0 transparent, and the",
        "// exact images (0xRRGGBBAA, rows top-down) the renderer draws in their place.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        f"namespace {namespace} {{",
    ]
    for t, (texels, palette, exact) in sorted(banners.items()):
        out.append(f"    inline constexpr uint8_t track{t}_texels[{W * H}] = {{")
        for k in range(0, len(texels), 32):
            out.append("        " + ", ".join(str(v) for v in texels[k : k + 32]) + ",")
        out.append("    };")
        out.append(f"    inline constexpr uint16_t track{t}_palette[256] = {{")
        for k in range(0, 256, 16):
            out.append("        " + ", ".join(f"0x{v:04X}" for v in palette[k : k + 16]) + ",")
        out.append("    };")
        out.append(f"    inline constexpr uint32_t track{t}_rgba[{W * H}] = {{")
        for k in range(0, len(exact), 16):
            out.append("        " + ", ".join(f"0x{v:08X}" for v in exact[k : k + 16]) + ",")
        out.append("    };")
    out.append("")
    out.append(f"    // Per track (0-{tracks - 1}).")
    for kind, ctype in (("texels", "uint8_t"), ("palette", "uint16_t"), ("rgba", "uint32_t")):
        names_list = ", ".join(f"track{t + 1}_{kind}" for t in range(tracks))
        plural = kind + ("s" if kind == "palette" else "")
        out.append(f"    inline constexpr const {ctype}* {plural}[{tracks}] = {{ {names_list} }};")
    out.append("}")
    path = os.path.join(ROOT, header)
    with open(path, "w", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    print(f"Wrote {header} ({len(banners)} banners)")


if __name__ == "__main__":
    preview = sys.argv[sys.argv.index("--preview") + 1] if "--preview" in sys.argv else None
    for game in GAMES:
        build(*game, preview)
