// Rush 2049 cars as Rush 2 car types 23-35 (docs/rush2049_research/cars.md); type 22 stays Rush 2's "no car" marker.
//
// Rush 2 keeps its per-car-type data in tables of 22 entries (0x800C06B4-0x800C0FDE): one row per table, or three
// rows (defaults, player 1, player 2) for the car options each player sets on the car select. us.toml (generated by
// tools/rush2049/cartypes.py) points every instruction that addresses them at 36-entry copies at 0x80200000 and
// re-strides the row arithmetic from 22 to 36. This file builds the copies at boot: Rush 2's entries, the "no car"
// marker type 22, then the 2049 cars' (types 23-35).

#include <cstdio>
#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <cmath>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <functional>
#include <map>
#include <set>
#include <mutex>
#include <string>
#include <vector>

#include "json/json.hpp"
#include "recomp.h"
#include "util/file.h"
#include "rush2_hooks.h"
#include "assets.h"
#include "car2049.h"
#include "track2049_convert.h"
#include "track2049.h"
#include "wings.h"

using namespace rush2::car2049;

namespace {
    constexpr int old_types = 22;
    constexpr int new_types = 36;

    struct Table {
        uint32_t old_base;
        uint32_t new_base;
        int size; // bytes per entry
        int rows;
    };

    // tools/rush2049/cartypes.py layout.
    constexpr Table tables[] = {
        { 0x800C06B4, 0x80200000, 4, 1 }, // steer/yaw force base
        { 0x800C070C, 0x80200090, 4, 1 }, // yaw damping base
        { 0x800C0764, 0x80200120, 4, 1 }, // car name pointers
        { 0x800C07E8, 0x802001B0, 1, 1 }, // type -> physics descriptor index
        { 0x800C0800, 0x802001D8, 4, 1 }, // suspension preload
        { 0x800C0858, 0x80200268, 4, 1 }, // mass
        { 0x800C08B0, 0x802002F8, 4, 1 }, // pitch/roll inertia
        { 0x800C090C, 0x80200388, 4, 1 }, // yaw inertia
        { 0x800C0964, 0x80200418, 4, 3 }, // setup weight value
        { 0x800C0A6C, 0x802005C8, 4, 3 }, // front wheel scale
        { 0x800C0B74, 0x80200778, 4, 3 }, // rear wheel scale
        { 0x800C0C7C, 0x80200928, 1, 3 }, // u8 setting
        { 0x800C0CD0, 0x80200998, 1, 3 }, // engine torque map index
        { 0x800C0D14, 0x80200A08, 1, 3 }, // drive flags
        { 0x800C0D68, 0x80200A78, 1, 3 }, // setting (yaw damping)
        { 0x800C0DAC, 0x80200AE8, 1, 3 }, // handling 0..10
        { 0x800C0E48, 0x80200B58, 1, 3 }, // car+0x59E
        { 0x800C0E8C, 0x80200BC8, 1, 3 }, // u8 setting
        { 0x800C0ED0, 0x80200C38, 1, 3 }, // u8 setting
        { 0x800C0F14, 0x80200CA8, 1, 3 }, // u8 setting
        { 0x800C0F58, 0x80200D18, 1, 3 }, // u8 setting
        { 0x800C0F9C, 0x80200D88, 1, 3 }, // u8 setting
    };

    // Race per-car arrays the car select also indexes by preview id (player * 36 + type): 44 entries moved to 72
    // (tools/rush2049/cartypes.py id_layout; us.toml relocates their users).
    struct IdArray {
        uint32_t old_base;
        uint32_t new_base;
        uint32_t stride;
    };
    constexpr int old_ids = 44;
    constexpr IdArray id_arrays[] = {
        { 0x8010C480, 0x80218000, 0x4E }, // part handles (func_80086700)
        { 0x8010F330, 0x802195F0, 0x1C }, // per-car callbacks
        { 0x80113F90, 0x80219DD0, 0x134 }, // car state (body node index at +0)
        { 0x801174F8, 0x8021F470, 0x7C }, // preview state (+1 loaded)
        { 0x800D9D40, 0x80221750, 0x2 }, // per-car s16
        { 0x800D97E8, 0x802217E0, 0x18 }, // car slot loads (func_80087CE4)
        { 0x80119858, 0x80221EA0, 0x1 }, // per-car byte (func_8008582C)
    };

    // Asset tables with room for the 2049 cars' files (indices 0x71 + n), and the car select's per-player car list
    // and carousel (us.toml points the game at these).
    constexpr uint32_t old_asset_offsets = 0x800C185C;
    constexpr uint32_t old_asset_sizes = 0x8001CD64;
    constexpr uint32_t asset_offsets = 0x80222A00;
    constexpr uint32_t asset_sizes = 0x80222C00;
    constexpr int old_assets = 0x71;
    constexpr int first_car_asset = 0x71;
    constexpr uint32_t car_slot_size = 0x8001CF28; // largest car asset (0xD1F0); func_800A37F4 allocates each slot

    // Per-type 16-byte tables: car boxes {front, rear, half width, height} (0x800CAC6C, 22 entries) and a second table
    // (0x800CADCC, 23 entries: entry 22 is a special case func_80059D24 picks), moved to 36 entries.
    constexpr uint32_t old_boxes = 0x800CAC6C;
    constexpr uint32_t boxes = 0x80223B00;
    constexpr uint32_t old_table16 = 0x800CADCC;
    constexpr uint32_t table16 = 0x80223D80;

    constexpr uint32_t car_list_counts = 0x803CB398; // s16 per player
    constexpr uint32_t car_names = 0x80223A00;      // "CAR1".."CAR13", 8 bytes each (part name prefixes)
    constexpr uint32_t name_table = 0x80200120;     // the relocated car name pointer table (type -> name)

    // Per-car options the player record keeps for each type (record + 0x584 + type * 13); types 22-35 live in side
    // slots, one per record, so the Controller Pak record keeps its layout.
    constexpr uint32_t record_block = 0x584;
    constexpr int block_size = 13;
    constexpr int durability_byte = 10;              // /100 = the weight (func_800B24AC)
    constexpr int engine_byte = 6;                   // ENGINE (func_800B2554)
    constexpr uint32_t side_slots = 0x80222E00;
    constexpr int side_slot_size = 0xC0;            // (36 - 22) * 13 = 182, rounded up
    constexpr int max_side_slots = 16;
    // Player records, 0x6C0 bytes each: the active players' (func_80097FCC) and the Controller Pak image's (4 paks of
    // 0x2200 bytes, src/track2049_records.cpp). Side slots are keyed by record address in these ranges.
    constexpr uint32_t record_size = 0x6C0;
    constexpr uint32_t player_records = 0x8010D740, player_records_end = 0x8010D740 + 8 * 0x6C0;
    constexpr uint32_t pak_records = 0x8004B220, pak_records_end = 0x8004B220 + 4 * 0x2200;
    bool in_save_area(uint32_t at) {
        return (at >= player_records && at < player_records_end) || (at >= pak_records && at < pak_records_end);
    }

    // Physics: Rush 2's descriptor pointers (0x800C07BC, indexed through the type -> index table) move to a 24-entry
    // copy, the 2049 cars' descriptors (Rush 2's 0xEC-byte layout, converted from 2049's 0xB4-byte ones as
    // tools/rush2049/cars.py does) follow, with copies of the tire curves they point at.
    constexpr uint32_t old_desc_ptrs = 0x800C07BC;
    constexpr uint32_t desc_ptrs = 0x80224100;
    constexpr int rush2_descs = 11;
    constexpr uint32_t tire_curves = 0x80224180;   // front, rear: 6 floats each
    constexpr uint32_t descs = 0x80224200;         // 13 x 0xEC
    constexpr uint32_t desc_size = 0xEC;
    // Relocated per-type tables (tools/rush2049/cartypes.py layout).
    constexpr uint32_t t_desc_index = 0x802001B0, t_preload = 0x802001D8, t_mass = 0x80200268, t_inertia = 0x802002F8,
                       t_yaw_inertia = 0x80200388, t_drive = 0x80200A08, t_weight = 0x80200418,
                       t_engine = 0x80200928;

    // Rush 2049 main code/data (inflated at 0x80086A50).
    constexpr uint32_t main49_rom = 0xB0CB10;
    constexpr uint32_t main49_vram = 0x80086A50;
    struct Main49 {
        std::vector<uint8_t> d;
        uint32_t w(uint32_t vram) const {
            size_t o = vram - main49_vram;
            return (uint32_t(d[o]) << 24) | (uint32_t(d[o + 1]) << 16) | (uint32_t(d[o + 2]) << 8) | d[o + 3];
        }
        float f(uint32_t vram) const {
            uint32_t v = w(vram);
            float r;
            memcpy(&r, &v, 4);
            return r;
        }
        int8_t b(uint32_t vram) const { return (int8_t)d[vram - main49_vram]; }
    };

    std::mutex side_mutex;

    // Paint: each car's asset copy keeps the 2049 palette at a fixed offset; it is rewritten as the pristine palette
    // times the main colour whenever the game builds the car's Rush 2 palette (func_8008582C).
    struct Paint {
        uint32_t texture_table = 0;          // file offset of the texture records
        uint32_t texture_count = 0;
        uint32_t first_texels = 0;           // file offset of the first texture's texels (sanity check)
        uint32_t palette = 0;                // file offset of the palette
        std::vector<uint8_t> colours;        // pristine RGBA5551 palette
        // Denting: the body's vertices (file offsets) and their pristine positions.
        std::vector<uint32_t> vertices;
        std::vector<std::array<int16_t, 3>> rest;
        float extent[3] = { 1.0f, 1.0f, 1.0f }; // half width, height, half length
        // Damage textures: the body's texture loads, each serving one panel (0 FR, 1 FL, 2 RR, 3 RL, 4 top), whose
        // G_SETTIMG reads the pristine texels or their scuffed copy by that panel's damage.
        struct DamageLoad {
            uint32_t at;        // file offset of the G_SETTIMG
            uint32_t pristine;  // file offsets of the texels
            uint32_t damaged;
            int panel;
        };
        std::vector<DamageLoad> damage_loads;
        // Rocket ZX exhaust flames (ROKTFLAMEG1-3): their vertices as modelled (at the origin, pointing back), and the
        // tile sizes of the scrolled flame texture's load list.
        struct Flame {
            std::vector<uint32_t> vertices;
            std::vector<std::array<int16_t, 3>> rest;
        };
        std::vector<Flame> flames;
        std::vector<std::pair<uint32_t, uint32_t>> flame_tiles; // G_SETTILESIZE offset, its w1
    };
    Paint paints[car_count];
    constexpr uint32_t car_banks = 0x80221750;      // s16 texture bank per preview id (moved from 0x800D9D40)
    constexpr uint32_t bank_table = 0x80119220;     // [bank] = texture records, count
    constexpr uint32_t colour_table = 0x800CE19C;   // RGBA per colour option
    constexpr int paint_ramps[3] = { 32, 64, 96 }; // COLOR 1-3 (main, accent, stripe colour)
    constexpr uint32_t car_palettes = 0x802217F4;   // per preview id, stride 0x18 (moved from 0x800D97FC)
    std::map<uint32_t, int> side_slot_of;            // record address -> side slot index
    std::map<uint32_t, int> selected_type_of;        // address of a record's selected-type byte -> full type

    std::atomic_bool cars_option = true;

    // Rush 2049's setup tables (docs/rush2049_research/cars.md �9), for applying a player's car options.
    struct Setup49 {
        bool loaded = false;
        float torque[6][3];      // 0x801110C4 [ENGINE][HANDLING]
        float trans[3][11];      // 0x801116D0 [HANDLING]: +1 mass, +2 torque, +3 gear ratio, +7 rear grip factors
        float gears[6];          // 0x80110EBC gear set 0
        float rear_grip[5];      // 0x8011121C [TIRES]
        float k_mass, k_frame0, k_frame1, k_yaw;
        float mass[car_count], inertia[car_count], yaw[car_count];
        int handling[car_count], tires[car_count], frame[car_count]; // the drones' setup (rows B, D, E)
        float frame_weight[6];   // 0x80111274 [FRAME]
        int colours[car_count][3]; // 0x80111604 / 0x80111648 / 0x8011168C: each car's COLOR 1-3 (func_800BB140)
        int rims[car_count];       // 0x8011157C: each car's TIRE RIMS (RIM01 + value, as in Rush 2)
        int engine[car_count];     // 0x80111080: the drones' ENGINE (row C)
        rush2::car2049::EngineLayer engine_sounds[8][2]; // 0x8010FD80 [ENGINE]
    };
    Setup49 setup49;
    bool is_2049(int type) {
        return type >= first_type && type < types && setup49.loaded;
    }

    bool cars_available() {
        return cars_option.load(std::memory_order_relaxed) && rush2::wings::rom_available();
    }

    void copy_entry(uint8_t* rdram, const Table& t, int row, int from_type, int to_type) {
        uint32_t src = t.old_base + (row * old_types + from_type) * t.size;
        uint32_t dst = t.new_base + (row * new_types + to_type) * t.size;
        for (int i = 0; i < t.size; i++) {
            MEM_B(0, (int32_t)(dst + i)) = MEM_B(0, (int32_t)(src + i));
        }
    }
}

// Called once at boot, before any menu or race reads the tables.
namespace {
    constexpr uint32_t old_prefixes = 0x800C64C4;   // texture name prefix per type ("TRK_", ...)
    constexpr uint32_t prefixes = 0x80224F00;       // 36 entries
    constexpr uint32_t no_prefix = 0x80224F90;      // "R49X_": matches no texture
    constexpr uint32_t engine_labels = 0x80225800;  // "ENGINE 1".."ENGINE 6", 16 bytes each (car options)
    constexpr int engine_levels = 6;
}

void rush2::car2049::init_tables(uint8_t* rdram) {
    for (int t = 0; t < types; t++) {
        MEM_W(0, (int32_t)(prefixes + t * 4)) = t < rush2_types ? MEM_W(0, (int32_t)(old_prefixes + t * 4)) : (int32_t)no_prefix;
    }
    for (int i = 0; i < engine_levels; i++) {
        std::string label = "ENGINE " + std::to_string(i + 1);
        for (size_t j = 0; j < 16; j++) {
            MEM_B(0, (int32_t)(engine_labels + i * 16 + j)) = j < label.size() ? label[j] : 0;
        }
    }
    const char* none = "R49X_";
    for (int i = 0; i <= 5; i++) {
        MEM_B(0, (int32_t)(no_prefix + i)) = none[i];
    }
    for (const Table& t : tables) {
        for (int row = 0; row < t.rows; row++) {
            for (int type = 0; type < new_types; type++) {
                // Type 22 and the 2049 types start as copies of the Pickup until the 2049 cars' data is filled in.
                copy_entry(rdram, t, row, type < old_types ? type : 0, type);
            }
        }
    }
    for (int t = 0; t < types; t++) {
        int from = t < rush2_types ? t : 0;
        for (int i = 0; i < 16; i++) {
            MEM_B(0, (int32_t)(boxes + t * 16 + i)) = MEM_B(0, (int32_t)(old_boxes + from * 16 + i));
            MEM_B(0, (int32_t)(table16 + t * 16 + i)) =
                MEM_B(0, (int32_t)(old_table16 + (t == rush2_types ? rush2_types : from) * 16 + i));
        }
    }
    for (const IdArray& a : id_arrays) {
        for (uint32_t i = 0; i < old_ids * a.stride; i++) {
            MEM_B(0, (int32_t)(a.new_base + i)) = MEM_B(0, (int32_t)(a.old_base + i));
        }
    }
}

namespace {
    // Car select name logos (asset 0x11, looked up by name through the overlay's type -> name table 0x803C7688):
    // 128x32 CI8 images in Rush 2's style, drawn from a 5x7 font, appended to the bank as "R49CARn".
    constexpr int select_bank = 0x11;
    constexpr uint32_t logo_names = 0x80224E00;    // 13 x 16 bytes
    constexpr uint32_t old_logo_table = 0x803C7688;
    const char* const display_names[car_count] = { "FORMULA 1", "8-BALL", "ROCKET ZX", "MAGNUM", "SUPER GT", "BRUISER",
        "LOCUST LX", "GX-2", "MINI XS", "VENOM", "CRUSHER", "EURO LX", "PANTHER" };

    const std::map<char, std::array<uint8_t, 7>> logo_font = {
        { 'A', { 0x0E, 0x11, 0x11, 0x1F, 0x11, 0x11, 0x11 } }, { 'B', { 0x1E, 0x11, 0x11, 0x1E, 0x11, 0x11, 0x1E } },
        { 'C', { 0x0E, 0x11, 0x10, 0x10, 0x10, 0x11, 0x0E } }, { 'E', { 0x1F, 0x10, 0x10, 0x1E, 0x10, 0x10, 0x1F } },
        { 'F', { 0x1F, 0x10, 0x10, 0x1E, 0x10, 0x10, 0x10 } }, { 'G', { 0x0E, 0x11, 0x10, 0x17, 0x11, 0x11, 0x0F } },
        { 'H', { 0x11, 0x11, 0x11, 0x1F, 0x11, 0x11, 0x11 } },
        { 'I', { 0x0E, 0x04, 0x04, 0x04, 0x04, 0x04, 0x0E } }, { 'K', { 0x11, 0x12, 0x14, 0x18, 0x14, 0x12, 0x11 } },
        { 'L', { 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x1F } }, { 'M', { 0x11, 0x1B, 0x15, 0x15, 0x11, 0x11, 0x11 } },
        { 'N', { 0x11, 0x11, 0x19, 0x15, 0x13, 0x11, 0x11 } }, { 'O', { 0x0E, 0x11, 0x11, 0x11, 0x11, 0x11, 0x0E } },
        { 'P', { 0x1E, 0x11, 0x11, 0x1E, 0x10, 0x10, 0x10 } }, { 'R', { 0x1E, 0x11, 0x11, 0x1E, 0x14, 0x12, 0x11 } },
        { 'S', { 0x0F, 0x10, 0x10, 0x0E, 0x01, 0x01, 0x1E } }, { 'T', { 0x1F, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04 } },
        { 'U', { 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x0E } }, { 'V', { 0x11, 0x11, 0x11, 0x11, 0x11, 0x0A, 0x04 } },
        { 'X', { 0x11, 0x11, 0x0A, 0x04, 0x0A, 0x11, 0x11 } }, { 'Z', { 0x1F, 0x01, 0x02, 0x04, 0x08, 0x10, 0x1F } },
        { '1', { 0x04, 0x0C, 0x04, 0x04, 0x04, 0x04, 0x0E } }, { '2', { 0x0E, 0x11, 0x01, 0x02, 0x04, 0x08, 0x1F } },
        { '8', { 0x0E, 0x11, 0x11, 0x0E, 0x11, 0x11, 0x0E } }, { '-', { 0x00, 0x00, 0x00, 0x1F, 0x00, 0x00, 0x00 } },
    };

    uint32_t be32(const std::vector<uint8_t>& d, size_t o) {
        return (uint32_t(d[o]) << 24) | (uint32_t(d[o + 1]) << 16) | (uint32_t(d[o + 2]) << 8) | d[o + 3];
    }
    void put32(std::vector<uint8_t>& d, size_t o, uint32_t v) {
        for (int i = 0; i < 4; i++) d[o + i] = uint8_t(v >> (24 - 8 * i));
    }
    uint16_t rgba5551(int r, int g, int b) { return uint16_t(((r >> 3) << 11) | ((g >> 3) << 6) | ((b >> 3) << 1) | 1); }

    // Italic capitals, blue shaded top to bottom, with a light outline and a dark drop shadow, as Rush 2's logos.
    void draw_select_logo(const std::string& text, std::vector<uint8_t>& texels, std::vector<uint8_t>& palette) {
        constexpr int w = 128, h = 32, sx = 2, sy = 3, advance = 6 * sx, top = 5;
        constexpr int shade_base = 1, shades = 7 * sy, outline = 30, shadow = 31;
        std::vector<uint8_t> ink(w * h, 0);
        int width = int(text.size()) * advance - sx;
        int x0 = (w - width) / 2 - 2;
        for (size_t c = 0; c < text.size(); c++) {
            auto g = logo_font.find(text[c]);
            if (g == logo_font.end()) continue;
            for (int y = 0; y < 7 * sy; y++) {
                int slant = (7 * sy - 1 - y) / 4;
                for (int x = 0; x < 5 * sx; x++) {
                    if (!(g->second[y / sy] & (0x10 >> (x / sx)))) continue;
                    int px = x0 + int(c) * advance + x + slant, py = top + y;
                    if (px >= 0 && px < w && py >= 0 && py < h) ink[py * w + px] = uint8_t(shade_base + y);
                }
            }
        }
        std::vector<uint8_t> img(w * h, 0);
        auto at = [&](const std::vector<uint8_t>& v, int x, int y) { return x >= 0 && x < w && y >= 0 && y < h ? v[y * w + x] : 0; };
        for (int y = 0; y < h; y++) {
            for (int x = 0; x < w; x++) {
                if (at(ink, x - 2, y - 2) || at(ink, x - 1, y - 2) || at(ink, x - 2, y - 1)) img[y * w + x] = shadow;
            }
        }
        for (int y = 0; y < h; y++) {
            for (int x = 0; x < w; x++) {
                bool near = false;
                for (int dy = -1; dy <= 1; dy++) for (int dx = -1; dx <= 1; dx++) near = near || at(ink, x + dx, y + dy);
                if (near) img[y * w + x] = outline;
                if (ink[y * w + x]) img[y * w + x] = ink[y * w + x];
            }
        }
        texels.resize(w * h);
        for (int y = 0; y < h; y++) memcpy(&texels[(h - 1 - y) * w], &img[y * w], w); // rows bottom-up
        std::vector<uint16_t> pal(256, 0);
        for (int i = 0; i < shades; i++) {
            float t = float(i) / float(shades - 1);
            pal[shade_base + i] = rgba5551(int(150 - 130 * t), int(190 - 160 * t), int(255 - 90 * t));
        }
        pal[outline] = rgba5551(214, 214, 224);
        pal[shadow] = rgba5551(8, 16, 72);
        palette.clear();
        for (uint16_t c : pal) { palette.push_back(uint8_t(c >> 8)); palette.push_back(uint8_t(c)); }
    }

    // Asset 0x11 with the 2049 cars' name logos added. The bank holds textures only: texels and palettes, then the
    // sorted texture (0x20-byte) and palette (0x18-byte) records.
    bool build_select_bank(const std::vector<uint8_t>& bank, std::vector<uint8_t>& out) {
        if (bank.size() < 0x28) return false;
        uint32_t tex = be32(bank, 8), pals = be32(bank, 12), ntex = be32(bank, 20), npal = be32(bank, 24);
        if (be32(bank, 16) != 0 || tex + ntex * 0x20 > bank.size() || pals + npal * 0x18 > bank.size()) return false;
        struct Rec { std::string name; std::vector<uint8_t> rec; std::string palette; };
        auto name_at = [&](size_t o) { return std::string(reinterpret_cast<const char*>(&bank[o]), strnlen(reinterpret_cast<const char*>(&bank[o]), 16)); };
        std::vector<Rec> textures, palettes;
        for (uint32_t i = 0; i < npal; i++) {
            size_t o = pals + i * 0x18;
            palettes.push_back({ name_at(o), std::vector<uint8_t>(bank.begin() + o, bank.begin() + o + 0x18), {} });
        }
        for (uint32_t i = 0; i < ntex; i++) {
            size_t o = tex + i * 0x20;
            uint16_t p = uint16_t((bank[o + 0x16] << 8) | bank[o + 0x17]);
            textures.push_back({ name_at(o), std::vector<uint8_t>(bank.begin() + o, bank.begin() + o + 0x20),
                                 p < npal ? palettes[p].name : std::string() });
        }
        out.assign(bank.begin(), bank.begin() + std::min(tex, pals));
        for (int k = 0; k < car_count; k++) {
            std::vector<uint8_t> texels, palette;
            draw_select_logo(display_names[k], texels, palette);
            while (out.size() % 8) out.push_back(0);
            uint32_t texel_off = uint32_t(out.size());
            out.insert(out.end(), texels.begin(), texels.end());
            uint32_t palette_off = uint32_t(out.size());
            out.insert(out.end(), palette.begin(), palette.end());
            std::string name = "R49CAR" + std::to_string(k + 1);
            std::vector<uint8_t> trec(0x20, 0), prec(0x18, 0);
            memcpy(trec.data(), name.data(), name.size());
            memcpy(prec.data(), name.data(), name.size());
            trec[16] = 0; trec[17] = 128; trec[18] = 0; trec[19] = 32;
            trec[20] = 0x01; trec[21] = 0x02;
            put32(trec, 24, texel_off);
            put32(trec, 28, 0x48008000);
            put32(prec, 16, 0x00FF8000);
            put32(prec, 20, palette_off);
            textures.push_back({ name, trec, name });
            palettes.push_back({ name, prec, {} });
        }
        auto by_name = [](const Rec& a, const Rec& b) { return a.name < b.name; };
        std::sort(textures.begin(), textures.end(), by_name);
        std::sort(palettes.begin(), palettes.end(), by_name);
        while (out.size() % 8) out.push_back(0);
        uint32_t tex_off = uint32_t(out.size());
        for (Rec& t : textures) {
            uint16_t index = 0xFFFF;
            for (size_t i = 0; i < palettes.size(); i++) {
                if (palettes[i].name == t.palette) index = uint16_t(i);
            }
            t.rec[0x16] = uint8_t(index >> 8);
            t.rec[0x17] = uint8_t(index);
            out.insert(out.end(), t.rec.begin(), t.rec.end());
        }
        uint32_t pal_off = uint32_t(out.size());
        for (const Rec& p : palettes) out.insert(out.end(), p.rec.begin(), p.rec.end());
        put32(out, 0, tex_off);
        put32(out, 4, uint32_t(out.size()));
        put32(out, 8, tex_off);
        put32(out, 12, pal_off);
        put32(out, 20, uint32_t(textures.size()));
        put32(out, 24, uint32_t(palettes.size()));
        return true;
    }
}

namespace {
    // The vertices the lists of model `name` load (G_VTX in the lists themselves: the G_DL calls they make go to
    // texture loads, or to the flames appended to the Rocket ZX's body).
    std::set<uint32_t> model_vertices(const std::vector<uint8_t>& car, const std::string& model) {
        uint32_t models = be32(car, 0), names = be32(car, 4), count = be32(car, 16);
        std::set<uint32_t> out;
        for (uint32_t m = 0; m < count; m++) {
            std::string name(reinterpret_cast<const char*>(&car[names + m * 0x18]),
                             strnlen(reinterpret_cast<const char*>(&car[names + m * 0x18]), 16));
            if (name != model) continue;
            uint32_t r = models + m * 0x34;
            for (uint32_t l = 0; l < be32(car, r) && l < 4; l++) {
                for (uint32_t pc = be32(car, r + 4 + l * 12 + 8); pc + 8 <= car.size(); pc += 8) {
                    uint32_t w0 = be32(car, pc), w1 = be32(car, pc + 4) & 0xFFFFFF;
                    if ((w0 >> 24) == 0xDF) break;
                    if ((w0 >> 24) == 0x01) {
                        uint32_t n = (w0 >> 12) & 0xFF;
                        for (uint32_t v = 0; v < n && w1 + v * 16 + 16 <= car.size(); v++) {
                            out.insert(w1 + v * 16);
                        }
                    }
                }
            }
        }
        return out;
    }

    std::array<int16_t, 3> vertex_at(const std::vector<uint8_t>& car, uint32_t v) {
        std::array<int16_t, 3> xyz;
        for (int i = 0; i < 3; i++) xyz[i] = int16_t((car[v + i * 2] << 8) | car[v + i * 2 + 1]);
        return xyz;
    }

    // The flame models, and the G_SETTILESIZEs of the texture-load list their lists call (the ROKTFLAME texture).
    void collect_flames(const std::vector<uint8_t>& car, Paint& p) {
        uint32_t models = be32(car, 0), names = be32(car, 4), count = be32(car, 16);
        uint32_t txld_start = be32(car, 28), txld_end = be32(car, 32);
        std::set<uint32_t> loads;
        for (const char* name : { "ROKTFLAMEG1", "ROKTFLAMEG2", "ROKTFLAMEG3" }) {
            Paint::Flame f;
            for (uint32_t v : model_vertices(car, name)) {
                f.vertices.push_back(v);
                f.rest.push_back(vertex_at(car, v));
            }
            if (f.vertices.empty()) return;
            p.flames.push_back(std::move(f));
            for (uint32_t m = 0; m < count; m++) {
                if (strncmp(reinterpret_cast<const char*>(&car[names + m * 0x18]), name, 16) != 0) continue;
                for (uint32_t o = be32(car, models + m * 0x34 + 4 + 8); o + 8 <= car.size() && car[o] != 0xDF; o += 8) {
                    uint32_t target = be32(car, o + 4) & 0xFFFFFF;
                    if (car[o] == 0xDE && target >= txld_start && target < txld_end) loads.insert(target);
                }
            }
        }
        for (uint32_t list : loads) {
            for (uint32_t o = list; o + 8 <= txld_end && car[o] != 0xDF; o += 8) {
                if (car[o] == 0xF2) p.flame_tiles.push_back({ o, be32(car, o + 4) });
            }
        }
    }

    // The body's (FRAME1, both LODs) vertices, for denting.
    void collect_body_vertices(const std::vector<uint8_t>& car, const std::string& prefix, Paint& p) {
        std::set<uint32_t> seen_vertices = model_vertices(car, prefix + "FRAME1");
        float lo[3] = { 0, 0, 0 }, hi[3] = { 0, 0, 0 };
        for (uint32_t v : seen_vertices) {
            std::array<int16_t, 3> xyz;
            for (int i = 0; i < 3; i++) {
                xyz[i] = int16_t((car[v + i * 2] << 8) | car[v + i * 2 + 1]);
                lo[i] = std::min(lo[i], float(xyz[i]));
                hi[i] = std::max(hi[i], float(xyz[i]));
            }
            p.vertices.push_back(v);
            p.rest.push_back(xyz);
        }
        for (int i = 0; i < 3; i++) p.extent[i] = std::max(1.0f, std::max(-lo[i], hi[i]));
    }

    // A scuffed copy of a painted CI8 texture, as Rush 2's D1 panel textures are of its D0 ones: the paint (2049's
    // ramps, entries 32-127, each a colour stepping towards black, §8 Paint) is mottled darker and lighter in blotches
    // a few texels wide, with a few bright scrapes. Other texels (glass, lights, trim) are kept.
    std::vector<uint8_t> scuff(const uint8_t* texels, uint32_t size, uint32_t width, uint32_t seed) {
        auto hash = [seed](int x, int y) {
            uint32_t h = uint32_t(x) * 73856093u ^ uint32_t(y) * 19349663u ^ seed * 83492791u;
            h ^= h >> 13;
            h *= 0x5BD1E995u;
            h ^= h >> 15;
            return float(h & 0xFFFF) / 65535.0f;
        };
        auto noise = [&](float x, float y) {
            int x0 = int(std::floor(x)), y0 = int(std::floor(y));
            float fx = x - x0, fy = y - y0;
            fx = fx * fx * (3.0f - 2.0f * fx);
            fy = fy * fy * (3.0f - 2.0f * fy);
            float a = hash(x0, y0) + (hash(x0 + 1, y0) - hash(x0, y0)) * fx;
            float b = hash(x0, y0 + 1) + (hash(x0 + 1, y0 + 1) - hash(x0, y0 + 1)) * fx;
            return a + (b - a) * fy;
        };
        std::vector<uint8_t> out(texels, texels + size);
        uint32_t height = std::max(1u, size / std::max(1u, width));
        std::vector<int> shift(size, 0);
        for (uint32_t i = 0; i < size; i++) {
            float x = float(i % width), y = float(i / width);
            float d = (noise(x / 5.0f, y / 4.0f) - 0.5f) * 11.0f + (noise(x / 2.0f + 17.0f, y / 2.0f + 5.0f) - 0.5f) * 5.0f;
            shift[i] = int(std::lround(d + 1.5f));
        }
        // Scrapes: short streaks of bare, bright paint, about one per 512 texels.
        uint32_t scrapes = std::max(1u, size / 512);
        for (uint32_t s = 0; s < scrapes; s++) {
            float x = hash(int(s), 101) * width, y = hash(int(s), 202) * height;
            float angle = (hash(int(s), 303) - 0.5f) * 1.2f;
            int length = 4 + int(hash(int(s), 404) * float(std::min(width, 12u)));
            for (int t = 0; t < length; t++) {
                int px = int(x + std::cos(angle) * t), py = int(y + std::sin(angle) * t);
                if (px < 0 || py < 0 || px >= int(width) || py >= int(height)) break;
                shift[py * width + px] = -6;
            }
        }
        for (uint32_t i = 0; i < size; i++) {
            int v = texels[i];
            if (v < 32 || v >= 128) continue;
            int first = v & ~31, last = first == 96 ? 126 : first + 31;
            out[i] = uint8_t(std::clamp(v + shift[i], first, last));
        }
        return out;
    }

    // Gives the body (FRAME1, both LODs) damage textures. Its lists call a texture-load list (in the file's [7]..[8]
    // range) before each run of triangles; they are rewritten (appended to the file) with every load of a painted
    // texture inlined before the triangles of each panel it textures, so each load can be pointed at the pristine
    // texels or at their scuffed copy (appended too) on its own. The relocator rebases the inlined G_SETTIMGs with
    // the list (they start pristine); rush2_car49_dent switches them.
    void add_damage_textures(std::vector<uint8_t>& car, const std::string& model, int car_index, Paint& p) {
        uint32_t models = be32(car, 0), names = be32(car, 4), count = be32(car, 16);
        uint32_t txld_start = be32(car, 28), txld_end = be32(car, 32);
        uint32_t record = 0;
        for (uint32_t m = 0; m < count; m++) {
            if (strncmp(reinterpret_cast<const char*>(&car[names + m * 0x18]), model.c_str(), 16) == 0) {
                record = models + m * 0x34;
            }
        }
        if (record == 0) return;
        auto align = [&car] { while (car.size() % 8) car.push_back(0); };

        // A texture-load list's commands (without its G_ENDDL), and the painted CI8 texels its G_SETTIMG loads.
        struct Load {
            std::vector<uint8_t> commands;
            int settimg = -1;      // offset in `commands`
            uint32_t texels = 0, damaged = 0;
        };
        std::map<uint32_t, Load> loads;
        std::map<uint32_t, uint32_t> scuffed; // pristine texels -> copy
        auto load_at = [&](uint32_t list) -> const Load& {
            auto it = loads.find(list);
            if (it != loads.end()) return it->second;
            Load l;
            uint32_t size = 0, width = 0;
            bool ci8 = false;
            for (uint32_t o = list; o + 8 <= txld_end && car[o] != 0xDF; o += 8) {
                uint32_t w0 = be32(car, o), w1 = be32(car, o + 4);
                switch (w0 >> 24) {
                case 0xFD:
                    if (l.settimg < 0) {
                        l.settimg = int(l.commands.size());
                        l.texels = w1 & 0xFFFFFF;
                    }
                    else {
                        l.settimg = -2; // more than one image: left alone
                    }
                    break;
                case 0xF3: // G_LOADBLOCK: lrs + 1 texels of the G_SETTIMG's size
                    if (l.settimg < 0) break;
                    size =((((w1 >> 12) & 0xFFF) + 1) << ((be32(car, list + l.settimg) >> 19) & 3)) >> 1;
                    break;
                case 0xF5: // the render tile: CI 8-bit, line in 64-bit words
                    if (((w1 >> 24) & 7) == 0) {
                        ci8 = ((w0 >> 21) & 7) == 2 && ((w0 >> 19) & 3) == 1;
                        width = ((w0 >> 9) & 0x1FF) * 8;
                    }
                    break;
                }
                l.commands.insert(l.commands.end(), car.begin() + o, car.begin() + o + 8);
            }
            if (l.settimg >= 0 && ci8 && width > 0 && size > 0 && l.texels + size <= car.size()) {
                uint32_t painted = 0;
                for (uint32_t i = 0; i < size; i++) painted += car[l.texels + i] >= 32 && car[l.texels + i] < 128;
                if (painted * 10 >= size) {
                    auto s = scuffed.find(l.texels);
                    if (s == scuffed.end()) {
                        std::vector<uint8_t> copy = scuff(&car[l.texels], size, width, l.texels * 31u + uint32_t(car_index));
                        align();
                        s = scuffed.emplace(l.texels, uint32_t(car.size())).first;
                        car.insert(car.end(), copy.begin(), copy.end());
                    }
                    l.damaged = s->second;
                }
            }
            return loads.emplace(list, std::move(l)).first->second;
        };

        // Panels: 0 front right, 1 front left, 2 rear right, 3 rear left, 4 top (+z is the front, +x the right side).
        auto panel_of = [&](const std::array<int16_t, 3>* v[3]) {
            float x = 0, y = 0, z = 0;
            for (int i = 0; i < 3; i++) {
                x += (*v[i])[0];
                y += (*v[i])[1];
                z += (*v[i])[2];
            }
            x /= 3.0f * p.extent[0];
            y /= 3.0f * p.extent[1];
            z /= 3.0f * p.extent[2];
            if (y > 0.5f) return 4;
            return (z > 0 ? 0 : 2) + (x > 0 ? 0 : 1);
        };

        uint32_t lods = std::min(be32(car, record), 4u);
        for (uint32_t lod = 0; lod < lods; lod++) {
            uint32_t list = be32(car, record + 4 + lod * 12 + 8);
            std::vector<uint8_t> out;
            std::vector<std::pair<uint32_t, int>> sites; // offset in `out` of an inlined G_SETTIMG, panel
            std::vector<std::pair<uint32_t, const Load*>> site_loads;
            std::array<int16_t, 3> buffer[64] = {};
            const Load* current = nullptr;
            int loaded_panel = -1;
            auto emit = [&out](uint32_t w0, uint32_t w1) {
                for (int i = 0; i < 4; i++) out.push_back(uint8_t(w0 >> (24 - 8 * i)));
                for (int i = 0; i < 4; i++) out.push_back(uint8_t(w1 >> (24 - 8 * i)));
            };
            // Indices are vertex * 2 (F3DEX2).
            auto panel = [&](uint32_t a, uint32_t b, uint32_t c) {
                const std::array<int16_t, 3>* v[3] = { &buffer[(a / 2) & 63], &buffer[(b / 2) & 63], &buffer[(c / 2) & 63] };
                return panel_of(v);
            };
            auto load_for = [&](int panel) {
                if (panel == loaded_panel) return;
                uint32_t at = uint32_t(out.size());
                out.insert(out.end(), current->commands.begin(), current->commands.end());
                site_loads.push_back({ at + current->settimg, current });
                sites.push_back({ at + current->settimg, panel });
                loaded_panel = panel;
            };
            for (uint32_t pc = list; pc + 8 <= car.size(); pc += 8) {
                uint32_t w0 = be32(car, pc), w1 = be32(car, pc + 4);
                uint8_t op = uint8_t(w0 >> 24);
                if (op == 0x01) { // G_VTX
                    uint32_t n = (w0 >> 12) & 0xFF, end = (w0 >> 1) & 0x7F, at = w1 & 0xFFFFFF;
                    for (uint32_t i = 0; i < n && end >= n && at + i * 16 + 6 <= car.size(); i++) {
                        buffer[(end - n + i) & 63] = vertex_at(car, at + i * 16);
                    }
                }
                if (op == 0xDE && (w1 & 0xFFFFFF) >= txld_start && (w1 & 0xFFFFFF) < txld_end) {
                    const Load& l = load_at(w1 & 0xFFFFFF);
                    if (l.damaged != 0) {
                        current = &l; // inlined before the triangles it textures
                        loaded_panel = -1;
                        continue;
                    }
                    current = nullptr;
                }
                if ((op == 0x05 || op == 0x06) && current != nullptr) {
                    int first = panel((w0 >> 16) & 0xFF, (w0 >> 8) & 0xFF, w0 & 0xFF);
                    load_for(first);
                    if (op == 0x06) {
                        int second = panel((w1 >> 16) & 0xFF, (w1 >> 8) & 0xFF, w1 & 0xFF);
                        if (second != first) { // split into two G_TRI1s
                            emit(0x05000000 | (w0 & 0xFFFFFF), 0);
                            load_for(second);
                            emit(0x05000000 | (w1 & 0xFFFFFF), 0);
                            continue;
                        }
                    }
                }
                emit(w0, w1);
                if (op == 0xDF) break;
            }
            if (sites.empty()) continue;
            align();
            uint32_t base = uint32_t(car.size());
            car.insert(car.end(), out.begin(), out.end());
            put32(car, record + 4 + lod * 12 + 8, base);
            for (size_t i = 0; i < sites.size(); i++) {
                const Load* l = site_loads[i].second;
                p.damage_loads.push_back({ base + sites[i].first, l->texels, l->damaged, sites[i].second });
            }
        }
    }

    // Points each panel's body texture loads at the pristine or scuffed texels (asset copy at `base`), as the
    // relocator would: 24-bit, rebased.
    void set_damage_textures(uint8_t* rdram, uint32_t base, const Paint& p, const float level[5]) {
        for (const Paint::DamageLoad& d : p.damage_loads) {
            uint32_t texels = level[d.panel] > 0.0f ? d.damaged : d.pristine;
            MEM_W(0, (int32_t)(base + d.at + 4)) = (int32_t)((base + texels) & 0xFFFFFF);
        }
    }

    // Finds the 2049 car whose asset copy race car `car` (0-7) uses, from its texture bank. Returns its asset base.
    const Paint* bank_instance(uint8_t* rdram, int bank, uint32_t& base);
    const Paint* car_instance(uint8_t* rdram, int id, uint32_t& base) {
        return bank_instance(rdram, (int16_t)MEM_H(0, (int32_t)(car_banks + id * 2)), base);
    }

    // The 2049 car whose asset copy texture bank `bank` holds.
    const Paint* bank_instance(uint8_t* rdram, int bank, uint32_t& base) {
        if (bank < 0 || bank >= (int)MEM_BU(0, (int32_t)0x800D5788)) return nullptr;
        uint32_t records = (uint32_t)MEM_W(0, (int32_t)(bank_table + bank * 8));
        uint32_t count = (uint32_t)MEM_W(0, (int32_t)(bank_table + bank * 8 + 4));
        for (const Paint& p : paints) {
            if (!p.colours.empty() && count == p.texture_count &&
                (uint32_t)MEM_W(0, (int32_t)(records + 24)) == records - p.texture_table + p.first_texels) {
                base = records - p.texture_table;
                return &p;
            }
        }
        return nullptr;
    }

    std::map<uint32_t, uint32_t> dented;   // asset copy base -> panel damage bits last applied
}

void rush2::car2049::init_assets(uint8_t* rdram) {
    for (int i = 0; i < old_assets; i++) {
        MEM_W(0, (int32_t)(asset_offsets + i * 4)) = MEM_W(0, (int32_t)(old_asset_offsets + i * 4));
        MEM_W(0, (int32_t)(asset_sizes + i * 4)) = MEM_W(0, (int32_t)(old_asset_sizes + i * 4));
    }
    for (int k = 0; k < car_count; k++) {
        MEM_W(0, (int32_t)(asset_offsets + (first_car_asset + k) * 4)) = 0;
        MEM_W(0, (int32_t)(asset_sizes + (first_car_asset + k) * 4)) = 0;
    }
    // Part name prefixes of the 2049 types, in the relocated name table.
    for (int k = 0; k < car_count; k++) {
        std::string name = "CAR" + std::to_string(k + 1);
        uint32_t at = car_names + k * 8;
        for (size_t i = 0; i <= name.size(); i++) {
            MEM_B(0, (int32_t)(at + i)) = i < name.size() ? name[i] : 0;
        }
        MEM_W(0, (int32_t)(name_table + (first_type + k) * 4)) = at;
    }
    // The 2049 cars' files, converted from the 2049 ROM.
    auto rom = rush2::wings::get_rom();
    if (rom == nullptr) {
        return;
    }
    for (int k = 0; k < car_count; k++) {
        std::string name = "R49CAR" + std::to_string(k + 1);
        for (size_t i = 0; i < 16; i++) {
            MEM_B(0, (int32_t)(logo_names + k * 16 + i)) = i < name.size() ? name[i] : 0;
        }
    }
    std::vector<uint8_t> bank, select;
    if (rush2::assets::read_original(rdram, select_bank, bank) && build_select_bank(bank, select)) {
        rush2::assets::replace(rdram, select_bank, select);
    }
    for (int k = 0; k < car_count; k++) {
        std::vector<uint8_t> car;
        std::string error;
        if (rush2::track2049::convert_car(*rom, k + 1, "CAR" + std::to_string(k + 1), car, error)) {
            Paint& p = paints[k];
            p.texture_table = be32(car, 8);
            p.texture_count = be32(car, 20);
            uint32_t palettes = be32(car, 12);
            if (be32(car, 24) >= 1 && p.texture_count >= 1) {
                p.first_texels = be32(car, p.texture_table + 24);
                p.palette = be32(car, palettes + 20);
                p.colours.assign(car.begin() + p.palette, car.begin() + p.palette + 512);
            }
            collect_body_vertices(car, "CAR" + std::to_string(k + 1), p);
            add_damage_textures(car, "CAR" + std::to_string(k + 1) + "FRAME1", k, p);
            collect_flames(car, p);
            // func_800A37F4 preallocates every car slot at this size (+ 0x400): the largest car asset.
            if (car.size() > (uint32_t)MEM_W(0, (int32_t)car_slot_size)) {
                MEM_W(0, (int32_t)car_slot_size) = (int32_t)((car.size() + 15) & ~15u);
            }
            rush2::assets::replace(rdram, first_car_asset + k, car);
        }
        else {
            fprintf(stderr, "[2049] Couldn't convert car %d: %s\n", k + 1, error.c_str());
        }
    }
}

// Car asset index = type + 0x1D (func_80087E88, func_800A37F4, func_80089CE4's caller): 2049 types use 0x71 + n.
extern "C" void rush2_car49_asset(uint8_t* rdram, recomp_context* ctx, uint64_t* reg) {
    int type = (int)(int32_t)*reg - 0x1D;
    if (type >= rush2::car2049::first_type && type < rush2::car2049::types) {
        *reg = (uint64_t)(int64_t)(first_car_asset + type - rush2::car2049::first_type);
    }
}

void rush2::car2049::append_to_car_list(uint8_t* rdram, int player) {
    if (!cars_available()) {
        return;
    }
    uint32_t count_at = car_list_counts + player * 2;
    int count = (int16_t)MEM_H(0, (int32_t)count_at);
    for (int k = 0; k < car_count && count < types; k++, count++) {
        MEM_B(0, (int32_t)(car_list + count * 2 + player)) = (uint8_t)(first_type + k);
    }
    MEM_H(0, (int32_t)count_at) = (int16_t)count;
}

// func_803B81F0 at 0x803B873C, after it listed a player's selectable Rush 2 cars: $a1 = player. The 2049 cars
// follow them (Unlock All Cars, src/cheats.cpp, rebuilds the list afterwards and appends them again).
extern "C" void rush2_car49_list(uint8_t* rdram, recomp_context* ctx) {
    rush2::car2049::append_to_car_list(rdram, (int)ctx->r5);
}

// Entry of the player-record per-car option getters and setters ($a0 = record, $a1 = type): types 22-35 are
// redirected to the record's side slot.
namespace {
    // A 2049 car's own colours and rims in its record block (func_800B266C / func_800B2640 / func_800B25D0 /
    // func_800B259C): MAIN is bits 5-7 of +1 and 0-1 of +2, ACCENT bits 2-6 of +2, STRIPE COLOR bits 3-7 of +3 (STRIPE
    // is bits 0-2), TIRE RIMS byte +4.
    void set_defaults(uint8_t* rdram, uint32_t block, int k) {
        MEM_B(0, (int32_t)(block + 4)) = (int8_t)setup49.rims[k];
        const int* c = setup49.colours[k];
        uint8_t b1 = MEM_BU(0, (int32_t)(block + 1)), b2 = MEM_BU(0, (int32_t)(block + 2)),
                b3 = MEM_BU(0, (int32_t)(block + 3));
        b1 = uint8_t((b1 & 0x1F) | ((c[0] & 7) << 5));
        b2 = uint8_t((b2 & 0x80) | ((c[1] & 0x1F) << 2) | ((c[0] >> 3) & 3));
        b3 = uint8_t((b3 & 7) | ((c[2] & 0x1F) << 3));
        MEM_B(0, (int32_t)(block + 1)) = (int8_t)b1;
        MEM_B(0, (int32_t)(block + 2)) = (int8_t)b2;
        MEM_B(0, (int32_t)(block + 3)) = (int8_t)b3;
    }

    // The side slots are kept in car2049.json (the Controller Pak record has no room for them), keyed by the
    // player record's address in the save area.
    std::filesystem::path side_path() {
        return recompui::file::get_app_folder_path() / "car2049.json";
    }

    void load_side_slots(uint8_t* rdram) {
        static bool loaded = false;
        if (loaded) {
            return;
        }
        loaded = true;
        std::ifstream f(side_path());
        if (!f) {
            return;
        }
        nlohmann::json j = nlohmann::json::parse(f, nullptr, false);
        if (!j.is_object() || !j.contains("records") || !j["records"].is_object()) {
            return;
        }
        if (j.contains("selected") && j["selected"].is_object()) {
            for (auto& [key, value] : j["selected"].items()) {
                uint32_t at = (uint32_t)std::strtoul(key.c_str(), nullptr, 16);
                if (in_save_area(at) && value.is_number_integer()) {
                    selected_type_of[at] = value.get<int>();
                }
            }
        }
        // Slots before version 5 started the 2049 cars with the Pickup's colours and rims (version 4: 2049's colours
        // reordered).
        bool old_colours = !j.contains("version") || !j["version"].is_number_integer() || j["version"].get<int>() < 5;
        for (auto& [key, value] : j["records"].items()) {
            uint32_t record = (uint32_t)std::strtoul(key.c_str(), nullptr, 16);
            if (!in_save_area(record) || !value.is_string() ||
                side_slot_of.size() >= max_side_slots) {
                continue;
            }
            std::string hex = value.get<std::string>();
            int slot = (int)side_slot_of.size();
            side_slot_of[record] = slot;
            for (int i = 0; i < (types - rush2_types) * block_size && i * 2 + 1 < (int)hex.size(); i++) {
                MEM_B(0, (int32_t)(side_slots + slot * side_slot_size + i)) = (uint8_t)std::stoi(hex.substr(i * 2, 2), nullptr, 16);
            }
            for (int t = first_type; t < types && old_colours && setup49.loaded; t++) {
                set_defaults(rdram, side_slots + slot * side_slot_size + (t - rush2_types) * block_size, t - first_type);
            }
        }
    }

    void save_side_slots(uint8_t* rdram) {
        nlohmann::json records = nlohmann::json::object();
        for (auto& [record, slot] : side_slot_of) {
            std::string hex;
            char b[3];
            for (int i = 0; i < (types - rush2_types) * block_size; i++) {
                snprintf(b, sizeof(b), "%02X", MEM_BU(0, (int32_t)(side_slots + slot * side_slot_size + i)));
                hex += b;
            }
            char key[16];
            snprintf(key, sizeof(key), "%08X", record);
            records[key] = hex;
        }
        std::ofstream f(side_path(), std::ios::trunc);
        if (f) {
            nlohmann::json selected = nlohmann::json::object();
            for (auto& [at, type] : selected_type_of) {
                char key[16];
                snprintf(key, sizeof(key), "%08X", at);
                selected[key] = type;
            }
            f << nlohmann::json{ { "version", 5 }, { "records", records }, { "selected", selected } }.dump(2) << "\n";
        }
    }
}

extern "C" void rush2_car49_record(uint8_t* rdram, recomp_context* ctx) {
    int type = (int)(ctx->r5 & 0xFF);
    if (type < rush2_types) {
        return;
    }
    uint32_t record = (uint32_t)ctx->r4;
    std::lock_guard lock{ side_mutex };
    load_side_slots(rdram);
    auto it = side_slot_of.find(record);
    int slot;
    if (it == side_slot_of.end()) {
        // The lowest slot no record holds (a deleted player's slot is freed).
        slot = (int)side_slot_of.size() % max_side_slots;
        for (int s = 0; s < max_side_slots; s++) {
            if (std::none_of(side_slot_of.begin(), side_slot_of.end(), [s](const auto& e) { return e.second == s; })) {
                slot = s;
                break;
            }
        }
        side_slot_of[record] = slot;
        // New slot: every extra type starts with the record's Pickup options, the car's own durability (2049 frame
        // weight, record byte +10 = weight x 100) and ENGINE 1.
        for (int t = rush2_types; t < types; t++) {
            uint32_t block = side_slots + slot * side_slot_size + (t - rush2_types) * block_size;
            for (int i = 0; i < block_size; i++) {
                MEM_B(0, (int32_t)(block + i)) = MEM_B(0, (int32_t)(record + record_block + i));
            }
            if (is_2049(t)) {
                int k = t - first_type;
                MEM_B(0, (int32_t)(block + durability_byte)) =
                    (int8_t)std::lround(setup49.frame_weight[setup49.frame[k]] * 100.0f);
                MEM_B(0, (int32_t)(block + engine_byte)) = 0;
                set_defaults(rdram, block, k);
            }
        }
    }
    else {
        slot = it->second;
    }
    // record' + 0x584 + type * 13 = side slot + (type - 22) * 13
    uint32_t fake = side_slots + slot * side_slot_size - record_block - rush2_types * block_size;
    ctx->r4 = (uint64_t)(int64_t)(int32_t)fake;
}

// Start of func_8005F338 ($a0 = address, $a1 = length): marks player-record bytes for the Controller Pak save. Returns
// true (skipping it) for side-slot addresses outside the save area.
extern "C" int rush2_car49_dirty(uint8_t* rdram, recomp_context* ctx) {
    uint32_t addr = (uint32_t)ctx->r4;
    if (addr >= side_slots && addr < side_slots + max_side_slots * side_slot_size) {
        std::lock_guard lock{ side_mutex };
        save_side_slots(rdram);
        return 1;
    }
    return 0;
}

void rush2::car2049::forget_record(uint8_t* rdram, uint32_t record) {
    std::lock_guard lock{ side_mutex };
    load_side_slots(rdram);
    bool changed = side_slot_of.erase(record) != 0;
    changed |= std::erase_if(selected_type_of, [record](const auto& e) {
        return e.first >= record && e.first < record + record_size;
    }) != 0;
    if (changed) {
        save_side_slots(rdram);
    }
}

namespace {
    uint32_t fbits(float f) {
        uint32_t v;
        memcpy(&v, &f, 4);
        return v;
    }


    // The 2049 cars' physics as Rush 2 data: descriptor, per-type table entries and box (tools/rush2049/cars.py to_r2,
    // with each car's drone setup).
    void build_physics(uint8_t* rdram, const Main49& m) {
        constexpr uint32_t desc_table = 0x80110D08, mass_t = 0x80110DD8, inertia_t = 0x80110E0C, yaw_t = 0x80110E44,
                           preload_t = 0x80110DA4, engine_t = 0x80111274, rear_lat_t = 0x8011121C,
                           gears_t = 0x80110EBC, trans_t = 0x801116D0, drive_t = 0x801114E4, box_t = 0x8011F844,
                           k_mass = 0x80124150, k_eng0 = 0x80124154, k_eng1 = 0x80124158, k_yawi = 0x8012415C,
                           setup_b = 0x8011103C, setup_d = 0x8011119C, setup_e = 0x80111230,
                           front_curve49 = 0x8011F814, rear_curve49 = 0x8011F82C;
        for (int i = 0; i < 6; i++) {
            MEM_W(0, (int32_t)(tire_curves + i * 4)) = m.w(front_curve49 + i * 4);
            MEM_W(0, (int32_t)(tire_curves + 0x18 + i * 4)) = m.w(rear_curve49 + i * 4);
        }
        uint32_t pickup = (uint32_t)MEM_W(0, (int32_t)(old_desc_ptrs + MEM_B(0, (int32_t)0x800C07E8) * 4));
        Setup49& s = setup49;
        for (int c = 0; c < 6; c++) {
            for (int b = 0; b < 3; b++) s.torque[c][b] = m.f(0x801110C4 + 12 * c + 4 * b);
            s.gears[c] = m.f(gears_t + 4 * c);
            s.frame_weight[c] = m.f(engine_t + 4 * c);
        }
        for (int b = 0; b < 3; b++) {
            for (int i = 0; i < 11; i++) s.trans[b][i] = m.f(trans_t + 0x2C * b + 4 * i);
        }
        for (int i = 0; i < 5; i++) s.rear_grip[i] = m.f(rear_lat_t + 4 * i);
        s.k_mass = m.f(k_mass);
        s.k_frame0 = m.f(k_eng0);
        s.k_frame1 = m.f(k_eng1);
        s.k_yaw = m.f(k_yawi);
        // Engine sounds (func_800D5E64 / func_800E0050): per ENGINE level, two 0x20-byte layers {s32 sound,
        // u16 base rpm, u16 span, u16 rpm points [3], u16, f32 volumes [3], f32}.
        for (int e = 0; e < 8; e++) {
            for (int l = 0; l < 2; l++) {
                uint32_t at = 0x8010FD80 + e * 0x40 + l * 0x20;
                EngineLayer& layer = s.engine_sounds[e][l];
                layer.sound = int32_t(m.w(at));
                layer.base = float(m.w(at + 4) >> 16);
                layer.span = float(m.w(at + 4) & 0xFFFF);
                layer.rpm[0] = float(m.w(at + 8) >> 16);
                layer.rpm[1] = float(m.w(at + 8) & 0xFFFF);
                layer.rpm[2] = float(m.w(at + 12) >> 16);
                for (int i = 0; i < 3; i++) layer.volume[i] = m.f(at + 16 + 4 * i);
            }
        }
        for (int k = 0; k < car_count; k++) s.engine[k] = std::clamp<int>(m.b(0x80111080 + k), 0, engine_levels - 1);
        s.loaded = true;
        // The Rush 2 car each 2049 car is closest to in kind (Formula 1 -> FORM1, 8-Ball -> HOTROD, Rocket ZX ->
        // GT90, Magnum -> CAMARO, Super GT -> VETTE, Bruiser -> PICKUP, Locust LX -> INTEG, GX-2 -> CONCPT, Mini XS ->
        // VWBUG, Venom -> VIPER, Crusher -> SUV, Euro LX -> BMW, Panther -> BUGAT).
        constexpr int analogue[car_count] = { 18, 17, 19, 5, 2, 0, 1, 11, 10, 9, 15, 4, 7 };
        for (int k = 0; k < car_count; k++) {
            int type = first_type + k;
            uint32_t d49 = m.w(desc_table + k * 4);
            uint32_t out = descs + k * desc_size;
            auto put = [&](uint32_t o, uint32_t v) { MEM_W(0, (int32_t)(out + o)) = v; };
            auto putf = [&](uint32_t o, float v) { put(o, fbits(v)); };
            // Drone setup (func_800EC2F8): row 0 of the setup tables, gear set 0.
            int B = m.b(setup_b + k), D = m.b(setup_d + k), E = m.b(setup_e + k);
            float tr[11];
            for (int i = 0; i < 11; i++) tr[i] = m.f(trans_t + 0x2C * B + 4 * i);
            float eng = m.f(engine_t + 4 * E);
            float d = eng - m.f(k_eng1);
            float mass = (m.f(mass_t + 4 * k) + (eng - m.f(k_eng0)) * m.f(k_mass)) * tr[1];
            float inertia = m.f(inertia_t + 4 * k) + d * 1000.0f;
            float yaw_inertia = m.f(yaw_t + 4 * k) + d * m.f(k_yawi);
            float rear_lat = m.f(rear_lat_t + 4 * D);
            s.mass[k] = m.f(mass_t + 4 * k);
            s.inertia[k] = m.f(inertia_t + 4 * k);
            s.yaw[k] = m.f(yaw_t + 4 * k);
            for (int i = 0; i < 3; i++) s.colours[k][i] = m.b(0x80111604 + 0x44 * i + k);
            s.rims[k] = std::clamp<int>(m.b(0x8011157C + k), 0, 20);
            s.handling[k] = B;
            s.tires[k] = D;
            s.frame[k] = E;
            for (uint32_t o = 0; o < 0x58; o += 4) put(o, m.w(d49 + o));                 // inertia, suspension
            put(0x58, MEM_W(0, (int32_t)(pickup + 0x58)));                               // Rush 2 only
            put(0x5C, MEM_W(0, (int32_t)(pickup + 0x5C)));
            put(0x60, m.w(d49 + 0x58));                                                  // drag, rolling resistance
            put(0x64, m.w(d49 + 0x5C));
            for (int i = 0; i < 4; i++) {                                                // tire curves
                uint32_t c = m.w(d49 + 0x60 + 4 * i);
                put(0x68 + 4 * i, c == rear_curve49 ? tire_curves + 0x18 : tire_curves);
            }
            putf(0x78, rear_lat * (1.0f - tr[7]));
            for (int i = 0; i < 12; i++) put(0x7C + 4 * i, m.w(d49 + 0x70 + 4 * i));     // wheel positions
            put(0xAC, m.w(d49 + 0xA0));                                                  // drivetrain inertia
            put(0xB0, m.w(d49 + 0xA4));                                                  // final drive
            put(0xB4, m.w(d49 + 0xA8));                                                  // clutch
            // Torque scale per gear: the analogue's. 2049's (trans+8 x 0x801110C4, 2.2 for every car) is above all
            // of Rush 2's (1.8-2.05), and the car select's ACCELERATION bar reads it (func_803B7F7C).
            uint32_t analogue_desc = (uint32_t)MEM_W(0, (int32_t)(old_desc_ptrs + MEM_B(0, (int32_t)(0x800C07E8 + analogue[k])) * 4));
            for (uint32_t o = 0xB8; o <= 0xC4; o += 4) put(o, MEM_W(0, (int32_t)(analogue_desc + o)));
            for (int i = 0; i < 6; i++) putf(0xC8 + 4 * i, m.f(gears_t + 4 * i) * tr[3]); // gear ratios (set 0)
            MEM_H(0, (int32_t)(out + 0xE0)) = 4;                                         // top gear
            MEM_H(0, (int32_t)(out + 0xE2)) = 0;
            put(0xE4, m.w(d49 + 0xAC));                                                  // shift thresholds
            put(0xE8, m.w(d49 + 0xB0));
            MEM_W(0, (int32_t)(desc_ptrs + (rush2_descs + k) * 4)) = out;
            MEM_B(0, (int32_t)(t_desc_index + type)) = (uint8_t)(rush2_descs + k);
            MEM_W(0, (int32_t)(t_preload + type * 4)) = m.w(preload_t + 4 * k);
            MEM_W(0, (int32_t)(t_mass + type * 4)) = fbits(mass);
            MEM_W(0, (int32_t)(t_inertia + type * 4)) = fbits(inertia);
            MEM_W(0, (int32_t)(t_yaw_inertia + type * 4)) = fbits(yaw_inertia);
            uint8_t drive = (uint8_t)m.b(drive_t + k);
            for (int row = 0; row < 3; row++) {
                MEM_B(0, (int32_t)(t_drive + row * types + type)) = drive;
            }
            for (int i = 0; i < 4; i++) {
                MEM_W(0, (int32_t)(boxes + type * 16 + i * 4)) = m.w(box_t + 16 * k + 4 * i);
            }
            // MAIN, ACCENT, STRIPE COLOR and TIRE RIMS start as the car's 2049 COLOR 1-3 and rims (2049's rims are
            // Rush 2's RIM01-RIM21, its palettes only darkened for its lighting).
            constexpr uint32_t t_colours[3] = { 0x80200C38, 0x80200CA8, 0x80200D88 }, t_rims = 0x80200B58;
            for (int row = 0; row < 3; row++) {
                for (int i = 0; i < 3; i++) MEM_B(0, (int32_t)(t_colours[i] + row * types + type)) = (int8_t)s.colours[k][i];
                MEM_B(0, (int32_t)(t_rims + row * types + type)) = (int8_t)s.rims[k];
            }
            // DURABILITY is 2049's FRAME (rush2_car49_setup_mass): its default is the car's own frame weight.
            for (int row = 0; row < 3; row++) {
                MEM_W(0, (int32_t)(t_weight + (row * types + type) * 4)) = fbits(eng);
            }
            // Steering, yaw damping, suspension setting and tire grip: Rush 2 tuning 2049 has no counterpart for (they
            // were the Pickup's for every 2049 car), taken from the analogue so the cars handle, and the car select's
            // bars read, differently.
            for (const Table& t : tables) {
                if (t.old_base == 0x800C06B4 || t.old_base == 0x800C070C || t.old_base == 0x800C0D68 ||
                    t.old_base == 0x800C0DAC) {
                    for (int row = 0; row < t.rows; row++) {
                        copy_entry(rdram, t, row, analogue[k], type);
                    }
                }
            }
        }
    }
}

void rush2::car2049::init_physics(uint8_t* rdram) {
    for (int i = 0; i < rush2_descs; i++) {
        MEM_W(0, (int32_t)(desc_ptrs + i * 4)) = MEM_W(0, (int32_t)(old_desc_ptrs + i * 4));
    }
    auto rom = rush2::wings::get_rom();
    Main49 m;
    if (rom == nullptr || rom->size() <= main49_rom ||
        !rush2::assets::inflate_raw(rom->data() + main49_rom, rom->size() - main49_rom, m.d)) {
        return;
    }
    build_physics(rdram, m);
}

// Car select name logo (0x803BB708, before the overlay's type -> name lookup): a1 = the logo's texture name.
extern "C" void rush2_car49_logo(uint8_t* rdram, recomp_context* ctx) {
    int type = (int8_t)MEM_B(0, (int32_t)ctx->r2);
    uint32_t name = type >= first_type && type < types ? logo_names + (type - first_type) * 16
                                                       : (uint32_t)MEM_W(0, (int32_t)(old_logo_table + type * 4));
    ctx->r5 = (uint64_t)(int64_t)(int32_t)name;
}

// End of func_8008582C (0x80085E1C, after the car's palette is stored): the game loads that palette (Rush 2's
// CARPALETTE with the main and accent ramps painted) as the TLUT for all of the car's textures. For a 2049 car it
// becomes the car's own 2049 palette painted as Rush 2049 paints it (func_800B10D4): entries 32-63, 64-95 and 96-126
// are generated from COLOR 1-3 (the colour, then 31 steps from it towards black, func_800B0EA0), and with COLOR 1
// white the grey ramp 1-31 is brightened by 1.25. MAIN, ACCENT and STRIPE COLOR are COLOR 1-3; the colour indices
// mean the same in both games (2049's 0x801226C0 table is Rush 2's 0x800CE19C, retuned), and Rush 2's is used so the
// car matches the select screen's swatches.
namespace {
    uint16_t rgba5551(uint8_t* rdram, int colour) {
        uint32_t rgba = (uint32_t)MEM_W(0, (int32_t)(colour_table + colour * 4));
        uint32_t r = rgba >> 24, g = (rgba >> 16) & 0xFF, b = (rgba >> 8) & 0xFF;
        return uint16_t(((r << 8) & 0xF800) | ((g << 3) & 0x7C0) | ((b >> 2) & 0x3E) | 1);
    }
    // func_800B0EA0: from colour a (t = 0) to colour b (t = 255).
    uint16_t blend5551(int t, uint16_t a, uint16_t b) {
        if (t == 0) return a;
        if (t >= 0xFF) return b;
        uint32_t u = 0xFF - t, out = 1;
        for (uint32_t mask : { 0xF800u, 0x7C0u, 0x3Eu }) {
            out |= ((((a & mask) * u) + ((b & mask) * t)) >> 8) & mask;
        }
        return uint16_t(out);
    }
}

extern "C" void rush2_car49_paint(uint8_t* rdram, recomp_context* ctx) {
    uint32_t sp = (uint32_t)ctx->r29;
    int id = (int16_t)MEM_H(0, (int32_t)(sp + 0xCA));
    int colours[3] = { MEM_BU(0, (int32_t)(sp + 0xD3)), MEM_BU(0, (int32_t)(sp + 0xD7)), MEM_BU(0, (int32_t)(sp + 0xDF)) };
    if (id < 0 || id >= 72) {
        return;
    }
    for (int& c : colours) {
        if (c >= 32) c = 0;
    }
    int bank = (int16_t)MEM_H(0, (int32_t)(car_banks + id * 2));
    if (bank < 0 || bank >= (int)MEM_BU(0, (int32_t)0x800D5788)) {
        return;
    }
    uint32_t records = (uint32_t)MEM_W(0, (int32_t)(bank_table + bank * 8));
    uint32_t count = (uint32_t)MEM_W(0, (int32_t)(bank_table + bank * 8 + 4));
    uint32_t palette = (uint32_t)MEM_W(0, (int32_t)(car_palettes + id * 0x18));
    for (const Paint& p : paints) {
        if (p.colours.empty() || count != p.texture_count ||
            (uint32_t)MEM_W(0, (int32_t)(records + 24)) != records - p.texture_table + p.first_texels) {
            continue;
        }
        for (int i = 0; i < 256; i++) {
            MEM_H(0, (int32_t)(palette + i * 2)) = uint16_t((p.colours[i * 2] << 8) | p.colours[i * 2 + 1]);
        }
        if (colours[0] == 0) {
            for (int i = 1; i < 32; i++) {
                uint16_t c = MEM_HU(0, (int32_t)(palette + i * 2));
                int v = std::min(0xFF, int(float(((c >> 11) & 0x1F) * 8) * 1.25f));
                MEM_H(0, (int32_t)(palette + i * 2)) = uint16_t(((v << 8) & 0xF800) | ((v << 3) & 0x7C0) | ((v >> 2) & 0x3E) | 1);
            }
        }
        for (int ramp = 0; ramp < 3; ramp++) {
            uint16_t colour = rgba5551(rdram, colours[ramp]);
            int first = paint_ramps[ramp];
            MEM_H(0, (int32_t)(palette + first * 2)) = colour;
            for (int t = 0, i = first + 1; t < (ramp == 2 ? 0xF0 : 0xF8); t += 8, i++) {
                MEM_H(0, (int32_t)(palette + i * 2)) = blend5551(t, colour, 0x0001);
            }
        }
        return;
    }
}

void rush2::car2049::set_option(bool enabled) {
    cars_option = enabled;
}

namespace {
    std::atomic<uint32_t> drone_cars = (uint32_t)rush2::car2049::DroneCars::AllTracks;
}

void rush2::car2049::set_drone_cars(DroneCars mode) {
    drone_cars = (uint32_t)mode;
}

bool rush2::car2049::available() {
    return cars_available();
}

// func_800A37F4, after a drone's random car type (0-15, $t7) is drawn from the seed just stepped ($a0) and before it
// is stored and checked against the cars already chosen: with the 2049 cars available the draw covers them too
// (types 23-35 after Rush 2's 16), as the Rush 2049 Computer Cars option allows. On a 2049 track with "Rush 2049
// Tracks" it covers only them (13 types, enough for the 7 drones to differ).
extern "C" void rush2_car49_drone(uint8_t* rdram, recomp_context* ctx) {
    using rush2::car2049::DroneCars;
    DroneCars mode = (DroneCars)drone_cars.load();
    if (!cars_available() || mode == DroneCars::Off) {
        return;
    }
    constexpr int rush2_drone_types = 16;
    uint32_t seed = (uint32_t)ctx->r4;
    uint32_t draw = (seed >> 16) & 0x7FFF;
    int pick;
    if (mode == DroneCars::Rush2049Tracks) {
        bool track_2049 = rush2::track2049::race_track() > 0 &&
            MEM_B(0, (int32_t)0x8010C3F0) == rush2::track2049::host_slot;
        if (!track_2049) {
            return;
        }
        pick = first_type + (int)(draw * uint32_t(car_count) / 32768);
    }
    else {
        pick = (int)(draw * uint32_t(rush2_drone_types + car_count) / 32768);
        if (pick >= rush2_drone_types) {
            pick = first_type + pick - rush2_drone_types;
        }
    }
    ctx->r15 = (uint64_t)pick;
}

// Start of func_8005CFB0, the per-frame callback of each race car ($a0 = its callback entry, car index at +0xE).
// Rush 2 shows damage by swapping panel models; a 2049 car has one body, so it is dented instead, as 2049 does: the
// body around each damaged corner (front/rear, left/right) is crushed towards the middle, and the roof down, by the
// panel's damage level (Rush 2's 2-bit levels at car + 0xE4, masks 0x800CE188 / shifts 0x800CE180; collisions raise
// a panel to 1, func_8006B730 / func_8009A264 / func_800715E8), and restored when it is repaired. A damaged panel's
// textures also turn to their scuffed copies, as Rush 2's damaged panels use its D1 textures.
extern "C" void rush2_car49_dent(uint8_t* rdram, recomp_context* ctx) {
    int car = (int16_t)MEM_H(0, (int32_t)((uint32_t)ctx->r4 + 0xE));
    if (car < 0 || car >= 8) {
        return;
    }
    uint32_t base;
    const Paint* p = car_instance(rdram, car, base);
    if (p == nullptr || p->vertices.empty()) {
        return;
    }
    uint32_t bits = (uint32_t)MEM_W(0, (int32_t)(0x801124A0 + car * 0x354 + 0xE4));
    float level[5];
    uint32_t key = 0;
    for (int k = 0; k < 5; k++) {
        uint32_t mask = (uint32_t)MEM_W(0, (int32_t)(0x800CE188 + k * 4));
        int v = int((bits & mask) >> MEM_BU(0, (int32_t)(0x800CE180 + k)));
        key |= uint32_t(v) << (k * 2);
        level[k] = v == 0 ? 0.0f : v == 1 ? 0.8f : 1.0f;
    }
    auto it = dented.find(base);
    if (it != dented.end() && it->second == key) {
        return;
    }
    dented[base] = key;
    set_damage_textures(rdram, base, *p, level);
    // Panels: 0 front right, 1 front left, 2 rear right, 3 rear left, 4 top. +z is the front, +x the right side.
    constexpr float corner_x[4] = { 1.0f, -1.0f, 1.0f, -1.0f }, corner_z[4] = { 1.0f, 1.0f, -1.0f, -1.0f };
    for (size_t i = 0; i < p->vertices.size(); i++) {
        const auto& r = p->rest[i];
        float x = r[0] / p->extent[0], y = r[1] / p->extent[1], z = r[2] / p->extent[2];
        // Jitter from the position, so vertices that share a position (seams, both LODs) move together.
        uint32_t h = (uint32_t(uint16_t(r[0])) * 73856093u) ^ (uint32_t(uint16_t(r[1])) * 19349663u) ^
                     (uint32_t(uint16_t(r[2])) * 83492791u);
        h ^= h >> 13;
        h *= 0x5BD1E995u;
        float jitter = float((h >> 8) & 0xFF) / 255.0f; // 0-1
        float dx = 0.0f, dy = 0.0f, dz = 0.0f;
        for (int k = 0; k < 4; k++) {
            if (level[k] == 0.0f) continue;
            float d = std::hypot((x - corner_x[k]) * 0.9f, (z - corner_z[k]) * 1.1f);
            float w = std::max(0.0f, 1.0f - d / 1.15f);
            w = w * w * (3.0f - 2.0f * w) * level[k] * (0.75f + 0.5f * jitter);
            dx -= corner_x[k] * w * 0.22f;  // towards the middle
            dz -= corner_z[k] * w * 0.20f;  // shorter
            dy -= std::max(0.0f, y) * w * 0.18f; // crumpled down
        }
        if (level[4] > 0.0f && y > 0.45f) {
            dy -= (y - 0.45f) / 0.55f * level[4] * (0.3f + 0.15f * jitter);
        }
        int16_t out[3] = {
            int16_t(std::lround(r[0] + dx * p->extent[0])),
            int16_t(std::lround(r[1] + dy * p->extent[1])),
            int16_t(std::lround(r[2] + dz * p->extent[2])),
        };
        for (int c = 0; c < 3; c++) {
            MEM_H(0, (int32_t)(base + p->vertices[i] + c * 2)) = (uint16_t)out[c];
        }
    }
}

// Start of func_80097F8C ($a0 = the record's selected-type byte, $a1 = type): the byte keeps the low 5 bits.
extern "C" void rush2_car49_select_set(uint8_t* rdram, recomp_context* ctx) {
    uint32_t at = (uint32_t)ctx->r4;
    int type = (int)(ctx->r5 & 0xFF);
    if (!in_save_area(at)) {
        return;
    }
    std::lock_guard lock{ side_mutex };
    load_side_slots(rdram);
    auto it = selected_type_of.find(at);
    if (type < first_type) {
        if (it == selected_type_of.end()) {
            return;
        }
        selected_type_of.erase(it);
    }
    else if (it != selected_type_of.end() && it->second == type) {
        return;
    }
    else {
        selected_type_of[at] = type;
    }
    save_side_slots(rdram);
}

// func_8009E6DC, after it copied the record's selected type (5 bits, at $v1) to the player ($s0 + 0x7EA): the full
// type when a 2049 car was selected, or the Pickup when the 2049 cars are off.
extern "C" void rush2_car49_select_get(uint8_t* rdram, recomp_context* ctx) {
    uint32_t at = (uint32_t)ctx->r3;
    uint32_t player = (uint32_t)ctx->r16;
    int type = MEM_BU(0, (int32_t)(player + 0x7EA));
    {
        std::lock_guard lock{ side_mutex };
        load_side_slots(rdram);
        auto it = selected_type_of.find(at);
        if (it != selected_type_of.end() && (it->second & 0x1F) == type) {
            type = it->second;
        }
    }
    if (type >= rush2_types && (!cars_available() || type >= types)) {
        type = 0;
    }
    MEM_B(0, (int32_t)(player + 0x7EA)) = (int8_t)type;
    // The engine sound (+0x7E9) was read from the ENGINE row with the 5-bit type; a 2049 car's ENGINE row is its power
    // (rush2_car49_setup_desc), so it keeps its default sound.
    if (is_2049(type)) {
        MEM_B(0, (int32_t)(player + 0x7E9)) = MEM_B(0, (int32_t)(t_engine + type));
    }
}

namespace {
    constexpr uint32_t physics_cars = 0x800F5470;  // Per race car: + index * 0x81C (src/wings_state.cpp)
    constexpr uint32_t physics_car_size = 0x81C;
    constexpr uint32_t car_throttle = 0x734;       // f32 gas pedal, 0-1
    constexpr uint32_t game_mode = 0x8010C0D0;     // 3 racing, 9 countdown, 10 race intro (src/input.cpp)
    // Where 2049 puts the flames (func_800930A4): 2 up and 5.6 back from the car's origin, in feet; model units are
    // 1/16 foot.
    constexpr float flame_origin[3] = { 0.0f, 2.0f * 16.0f, -5.6f * 16.0f };

    struct FlameState {
        float scale[3] = { 0.25f, 0.25f, 0.55f };
        uint32_t seed = 0x2049;
    };
    std::map<uint32_t, FlameState> flame_states;    // asset copy base -> its flames

    float flame_random(FlameState& s) {
        s.seed = s.seed * 0x41C64E6D + 0x3039;
        return float((s.seed >> 16) & 0x7FFF) / 32768.0f;
    }

    // One 2049 frame (1/30 s) of func_800930A4's flame scales: the first two flames' lengths and the third's width
    // flicker around a size that grows with the engine (2049: rpm; here the gas pedal), and shrink back when idle.
    void step_flames(FlameState& s, float gas) {
        if (gas > 0.05f) {
            float size = std::min(1.0f, 0.2f + gas * 0.8f);
            s.scale[0] = size - flame_random(s) * 0.15f;
            s.scale[1] = std::min(1.0f, size + 0.15f) - flame_random(s) * 0.15f;
            s.scale[2] = 0.6f - flame_random(s) * 0.1f;
            return;
        }
        for (int i = 0; i < 2; i++) {
            if (s.scale[i] < 0.28f) {
                s.scale[i] = 0.25f - flame_random(s) * 0.15f;
            }
            else {
                s.scale[i] = std::max(0.2f, s.scale[i] - (flame_random(s) * 0.025f + 0.01f));
            }
        }
        s.scale[2] = s.scale[2] < 0.58f ? 0.55f - flame_random(s) * 0.1f
                                        : std::max(0.5f, s.scale[2] - (flame_random(s) * 0.025f + 0.01f));
    }

    void place_flames(uint8_t* rdram, const Paint& p, uint32_t base, const FlameState& s) {
        for (size_t f = 0; f < p.flames.size() && f < 3; f++) {
            // Flames 1 and 2 stretch along their length (z), flame 3 across (x, y).
            float k[3] = { f == 2 ? s.scale[2] : 1.0f, f == 2 ? s.scale[2] : 1.0f, f == 2 ? 1.0f : s.scale[f] };
            for (size_t i = 0; i < p.flames[f].vertices.size(); i++) {
                for (int c = 0; c < 3; c++) {
                    float v = p.flames[f].rest[i][c] * k[c] + flame_origin[c];
                    MEM_H(0, (int32_t)(base + p.flames[f].vertices[i] + c * 2)) = (uint16_t)(int16_t)std::lround(v);
                }
            }
        }
    }

    // func_800BD104 for the flame texture: its tile origin s (uls) in every G_SETTILESIZE, halved per mipmap level.
    void scroll_flames(uint8_t* rdram, const Paint& p, uint32_t base, int value) {
        int size = -1;
        for (auto [offset, w1] : p.flame_tiles) {
            uint32_t addr = base + offset;
            if (MEM_BU(0, (int32_t)addr) != 0xF2) return;
            int extent = int((w1 >> 12) & 0xFFF) + 4;
            if (size < 0) {
                size = extent;
            }
            else {
                while (extent < size) {
                    size >>= 1;
                    value >>= 1;
                }
            }
            uint32_t w0 = (uint32_t)MEM_W(0, (int32_t)addr);
            MEM_W(0, (int32_t)addr) = (int32_t)((w0 & 0xFF000FFF) | (((uint32_t)value & 0xFFF) << 12));
        }
    }
}

void rush2::car2049::animate(uint8_t* rdram) {
    using clock = std::chrono::steady_clock;
    static clock::time_point start = clock::now(), last_frame{};
    static double flame_time = 0.0;
    clock::time_point now = clock::now();
    if (now - last_frame < std::chrono::microseconds(16667)) {
        return;
    }
    double dt = std::min(0.1, std::chrono::duration<double>(now - last_frame).count());
    last_frame = now;
    bool any = false;
    for (const Paint& p : paints) any = any || !p.flames.empty();
    if (!any) {
        return;
    }
    // 2049 runs its flames at 30 fps and scrolls the texture 16 units (4 texels) per 1/60 s, wrapping at 512.
    flame_time += dt;
    bool step = flame_time >= 1.0 / 30.0;
    if (step) flame_time = std::fmod(flame_time, 1.0 / 30.0);
    int scroll = int(std::chrono::duration<double>(now - start).count() * 60.0 * 16.0) % 512 >> 2;

    // Gas pedal of each race car's asset copy.
    std::map<uint32_t, float> gas_of;
    int mode = MEM_W(0, (int32_t)game_mode);
    if (mode == 3 || mode == 9 || mode == 10) {
        for (int car = 0; car < 8; car++) {
            uint32_t base;
            if (car_instance(rdram, car, base) != nullptr) {
                uint32_t bits = (uint32_t)MEM_W(0, (int32_t)(physics_cars + car * physics_car_size + car_throttle));
                float gas;
                memcpy(&gas, &bits, 4);
                gas_of[base] = std::clamp(gas, 0.0f, 1.0f);
            }
        }
    }
    int banks = MEM_BU(0, (int32_t)0x800D5788);
    for (int bank = 0; bank < banks; bank++) {
        uint32_t base;
        const Paint* p = bank_instance(rdram, bank, base);
        if (p == nullptr || p->flames.empty()) {
            continue;
        }
        FlameState& s = flame_states[base];
        if (step) {
            auto g = gas_of.find(base);
            step_flames(s, g != gas_of.end() ? g->second : 0.0f);
        }
        place_flames(rdram, *p, base, s);
        scroll_flames(rdram, *p, base, scroll);
    }
}

// Car options on the 2049 cars (docs/rush2049_research/cars.md §9). Rush 2's rows map onto Rush 2049's setup:
//   ENGINE     -> 2049 ENGINE (power level 1-6: torque 0x801110C4 rows). Rush 2's engine is a sound, a different kind
//                 of effect: the 2049 cars keep their default sound and the row shows ENGINE 1-6.
//   SUSPENSION -> 2049 HANDLING (0x801116D0: gear ratio factor, torque column). Rush 2's yaw damping and suspension
//                 curve (incl. WHEELIE) are dropped for these cars.
//   TIRES      -> 2049 TIRES (rear grip 0x8011121C) from the D (drift) digit of S0 D0 .. S2 D2; the off-road tires
//                 take 2049's full-grip set. Rush 2's steering, yaw and off-road values are dropped.
//   DURABILITY -> 2049 FRAME (frame weight 0x80111274: mass and inertia); the value is the weight.
//   TRANSMISSION, colours, TIRE RIMS, HORN, TORQUE, TIRE SIZE: Rush 2's, unchanged.
// A player's choices are applied to a copy of the car's descriptor (one per race car) and to the car's mass fields.
namespace {
    constexpr uint32_t car_descs = 0x80225000;      // 8 x 0xEC: per race car descriptor copies
    constexpr uint32_t mass_scale = 0x800C0FE0, weight_mass = 0x800CFBCC, gravity_mass = 0x80110018;

    float f32_at(uint8_t* rdram, uint32_t addr) {
        uint32_t v = (uint32_t)MEM_W(0, (int32_t)addr);
        float f;
        memcpy(&f, &v, 4);
        return f;
    }
    void put_f32(uint8_t* rdram, uint32_t addr, float f) {
        MEM_W(0, (int32_t)addr) = (int32_t)fbits(f);
    }
    // A car's 2049 options from its table row (0 = the defaults, 1-2 = the players'): ENGINE (power level) and the
    // DURABILITY value as 2049's FRAME weight. HANDLING stays the car's own 2049 setup; TIRES and SUSPENSION are
    // Rush 2's rows with their Rush 2 effect.
    struct Choices {
        int engine;
        float frame;
    };
    Choices choices_of(uint8_t* rdram, int row, int type) {
        Choices c{};
        int k = type - first_type;
        if (row == 0) {
            c.frame = setup49.frame_weight[setup49.frame[k]];
            return c;
        }
        c.engine = std::clamp<int>((int8_t)MEM_B(0, (int32_t)(t_engine + row * types + type)), 0, engine_levels - 1);
        c.frame = std::clamp(f32_at(rdram, t_weight + (row * types + type) * 4), 0.0f, 1.0f);
        return c;
    }
    // ENGINE's torque scale: 2049's torque for the power level over level 1's, with the car's own HANDLING column.
    float engine_torque(int type, int engine) {
        const Setup49& s = setup49;
        int h = s.handling[type - first_type];
        return s.torque[engine][h] / s.torque[0][h];
    }
    // func_8008DBA0's row: the player's (1 + player index) for a human-driven car, else 0.
    int car_row(uint8_t* rdram, uint32_t car) {
        return (int8_t)MEM_B(0, (int32_t)(car + 0x7E8)) == 2 ? (int16_t)MEM_H(0, (int32_t)(car + 0x7E0)) + 1 : 0;
    }
}

// func_8008DBA0 (car init) at 0x8008DC1C, after it stored the car's descriptor ($fp) at car + 0 ($s2): a 2049 car
// driven by a player gets its own copy with the ENGINE choice applied.
extern "C" void rush2_car49_setup_desc(uint8_t* rdram, recomp_context* ctx) {
    uint32_t car = (uint32_t)ctx->r18;
    int type = MEM_BU(0, (int32_t)(car + 0x7EA));
    int slot = int((car - physics_cars) / physics_car_size);
    if (!is_2049(type) || slot < 0 || slot >= 8) {
        return;
    }
    int row = car_row(rdram, car);
    if (row == 0) {
        return;
    }
    Choices c = choices_of(rdram, row, type);
    uint32_t desc = (uint32_t)ctx->r30;
    uint32_t copy = car_descs + slot * desc_size;
    for (uint32_t o = 0; o < desc_size; o += 4) {
        MEM_W(0, (int32_t)(copy + o)) = MEM_W(0, (int32_t)(desc + o));
    }
    float torque = engine_torque(type, c.engine);
    for (uint32_t o = 0xB8; o <= 0xC4; o += 4) {
        put_f32(rdram, copy + o, f32_at(rdram, copy + o) * torque);
    }
    MEM_W(0, (int32_t)car) = (int32_t)copy;
    ctx->r30 = (uint64_t)(int64_t)(int32_t)copy;
}

// func_8008DBA0 at 0x8008DD00, after the car's mass (+0x5B0, with the durability weight), inertias (+0x5B4, +0x644)
// and weight force (+0x5AC): for a 2049 car they come from 2049's FRAME (func_800D0B14) with the DURABILITY value as
// the frame weight, in place of Rush 2's weight adjustment.
extern "C" void rush2_car49_setup_mass(uint8_t* rdram, recomp_context* ctx) {
    uint32_t car = (uint32_t)ctx->r18;
    int type = MEM_BU(0, (int32_t)(car + 0x7EA));
    if (!is_2049(type)) {
        return;
    }
    int row = car_row(rdram, car);
    Choices c = choices_of(rdram, row, type);
    const Setup49& s = setup49;
    int k = type - first_type;
    float weight_delta = f32_at(rdram, t_weight + (row * types + type) * 4) - f32_at(rdram, t_weight + type * 4);
    float mass49 = (s.mass[k] + (c.frame - s.k_frame0) * s.k_mass) * s.trans[s.handling[k]][1];
    float mass = f32_at(rdram, car + 0x5B0) + (mass49 - f32_at(rdram, t_mass + type * 4) -
                                                weight_delta * f32_at(rdram, weight_mass)) * f32_at(rdram, mass_scale);
    float d = c.frame - s.k_frame1;
    put_f32(rdram, car + 0x5B0, mass);
    put_f32(rdram, car + 0x5B4, s.inertia[k] + d * 1000.0f);
    put_f32(rdram, car + 0x644, s.yaw[k] + d * s.k_yaw);
    put_f32(rdram, car + 0x5AC, mass * f32_at(rdram, gravity_mass));
}

// Car select, func_803B9478: changing a player's ENGINE value. At 0x803B9E3C the row byte is at $v1 + 0x24 (type $a3,
// direction $a1); at 0x803B9E78 the new value is in $v0, after Rush 2's wrap at 10 and its skip of a locked engine.
// The 2049 cars have 6 engines, none locked.
namespace {
    int engine_before = -1;
}

extern "C" void rush2_car49_engine_before(uint8_t* rdram, recomp_context* ctx) {
    engine_before = (int8_t)MEM_B(0, (int32_t)((uint32_t)ctx->r3 + 0x24));
}

extern "C" void rush2_car49_engine_value(uint8_t* rdram, recomp_context* ctx) {
    int type = (int)(int8_t)ctx->r7;
    int before = engine_before;
    engine_before = -1;
    if (!is_2049(type) || before < 0) {
        return;
    }
    int step = (int64_t)ctx->r5 > 0 ? 1 : -1;
    int value = (std::clamp(before, 0, engine_levels - 1) + step + engine_levels) % engine_levels;
    MEM_B(0, (int32_t)((uint32_t)ctx->r3 + 0x24)) = (int8_t)value;
    ctx->r2 = (uint64_t)value;
}

int rush2::car2049::engine_sound(uint8_t* rdram, int type, int value) {
    return is_2049(type) ? (int8_t)MEM_B(0, (int32_t)(t_engine + type)) : value;
}

// Car select, func_803BC048: 0x803BC4F0 starts the ENGINE row's value text (the horn and engine names share one string
// table, so the row is told by its case); at 0x803BC63C the text is in $s0 (player $s2, the players' current types at
// $s6). A 2049 car's ENGINE row reads ENGINE 1-6.
namespace {
    bool engine_row_text = false;
}

extern "C" void rush2_car49_engine_text(uint8_t* rdram, recomp_context* ctx) {
    engine_row_text = true;
}

extern "C" void rush2_car49_option_text(uint8_t* rdram, recomp_context* ctx) {
    bool engine_row = engine_row_text;
    engine_row_text = false;
    int player = (int)ctx->r18;
    if (!engine_row || ctx->r16 == 0 || player < 0 || player > 1) {
        return;
    }
    int type = (int8_t)MEM_B(0, (int32_t)((uint32_t)ctx->r22 + player));
    if (is_2049(type)) {
        int value = std::clamp<int>((int8_t)MEM_B(0, (int32_t)(t_engine + (player + 1) * types + type)), 0,
                                    engine_levels - 1);
        ctx->r16 = (uint64_t)(int64_t)(int32_t)(engine_labels + value * 16);
    }
}

// Car select stat bars (func_803B7F7C, player $s4; the bars' types at 0x803CB362): ACCELERATION reads the weight
// (func_8008DB04) and the torque scale of gear 1 (descriptor +0xB8), TOP SPEED gear 3's torque scale over the top gear
// ratio (+0xC0 / +0xDC), CONTROL and DRIFTING the TIRES and SUSPENSION rows. For the duration of the call the car's
// descriptor is replaced by a copy whose torque scales carry the player's TORQUE curve (Rush 2's own bars leave it
// out) and, for a 2049 car, its ENGINE level; a 2049 car's weight is its FRAME mass (rush2_car49_setup_mass).
// TORQUE picks one of three full-throttle torque curves shared by every car (0x800C0CC0: LOW, STANDARD, HIGH, and
// ROCKET = STANDARD's), so each counts by a measured factor: in races with every car forced onto each curve, time from
// the start to 5000 rpm in gear 3 was 7.58 / 7.41 / 7.47 s (ACCELERATION: STANDARD's time over the curve's) and the
// mean top-gear rpm on the straights 7165 / 7096 / 7051 (TOP SPEED, whose bar term is linear in force:
// (rpm / STANDARD's)^2). LOW pulls hardest below about 3500 and above about 7000 rpm, HIGH only between about 5200
// and 6600, where the cars pass but don't settle.
namespace {
    constexpr uint32_t bar_types = 0x803CB362;
    constexpr uint32_t bar_descs = 0x80225A00;      // 2 x 0xEC
    constexpr uint32_t t_torque = 0x80200998;
    struct BarSwap {
        bool active = false;
        uint32_t ptr_at = 0, ptr = 0, mass_at = 0, mass = 0;
    };
    BarSwap bar_swap;

    constexpr float torque_accel[4] = { 7.41f / 7.58f, 1.0f, 7.41f / 7.47f, 1.0f };
    constexpr float torque_top[4] = { (7165.0f / 7096.0f) * (7165.0f / 7096.0f), 1.0f,
                                      (7051.0f / 7096.0f) * (7051.0f / 7096.0f), 1.0f };
}

extern "C" void rush2_car49_bars_begin(uint8_t* rdram, recomp_context* ctx) {
    bar_swap.active = false;
    int player = (int)ctx->r20;
    if (player < 0 || player > 1) {
        return;
    }
    int type = (int8_t)MEM_B(0, (int32_t)(bar_types + player));
    if (type < 0 || type >= types || type == rush2_types) {
        return;
    }
    int row = player + 1;
    uint32_t ptr_at = desc_ptrs + MEM_BU(0, (int32_t)(t_desc_index + type)) * 4;
    uint32_t desc = (uint32_t)MEM_W(0, (int32_t)ptr_at);
    uint32_t copy = bar_descs + player * desc_size;
    for (uint32_t o = 0; o < desc_size; o += 4) {
        MEM_W(0, (int32_t)(copy + o)) = MEM_W(0, (int32_t)(desc + o));
    }
    int chosen = std::clamp<int>((int8_t)MEM_B(0, (int32_t)(t_torque + row * types + type)), 0, 3);
    int stock = std::clamp<int>((int8_t)MEM_B(0, (int32_t)(t_torque + type)), 0, 3);
    float engine = is_2049(type) ? engine_torque(type, choices_of(rdram, row, type).engine) : 1.0f;
    put_f32(rdram, copy + 0xB8, f32_at(rdram, copy + 0xB8) * engine * torque_accel[chosen] / torque_accel[stock]);
    put_f32(rdram, copy + 0xC0, f32_at(rdram, copy + 0xC0) * engine * torque_top[chosen] / torque_top[stock]);
    bar_swap = { true, ptr_at, desc, 0, 0 };
    MEM_W(0, (int32_t)ptr_at) = (int32_t)copy;
    if (is_2049(type)) {
        // func_8008DB04 = ((weight[row] - weight[0]) * k + mass[type] + ...) * scale; the car gets
        // (2049 frame mass + ...) * scale, so mass[type] stands in as the frame mass less the weight term.
        const Setup49& s = setup49;
        int k = type - first_type;
        float frame = choices_of(rdram, row, type).frame;
        float mass49 = (s.mass[k] + (frame - s.k_frame0) * s.k_mass) * s.trans[s.handling[k]][1];
        float weight_delta = f32_at(rdram, t_weight + (row * types + type) * 4) - f32_at(rdram, t_weight + type * 4);
        bar_swap.mass_at = t_mass + type * 4;
        bar_swap.mass = (uint32_t)MEM_W(0, (int32_t)bar_swap.mass_at);
        put_f32(rdram, bar_swap.mass_at, mass49 - weight_delta * f32_at(rdram, weight_mass));
    }
}

extern "C" void rush2_car49_bars_end(uint8_t* rdram, recomp_context* ctx) {
    if (!bar_swap.active) {
        return;
    }
    MEM_W(0, (int32_t)bar_swap.ptr_at) = (int32_t)bar_swap.ptr;
    if (bar_swap.mass_at != 0) {
        MEM_W(0, (int32_t)bar_swap.mass_at) = (int32_t)bar_swap.mass;
    }
    bar_swap.active = false;
}

int rush2::car2049::engine_level(uint8_t* rdram, uint32_t car) {
    int type = MEM_BU(0, (int32_t)(car + 0x7EA));
    if (!is_2049(type)) {
        return -1;
    }
    int row = car_row(rdram, car);
    return row == 0 ? setup49.engine[type - first_type] : choices_of(rdram, row, type).engine;
}

bool rush2::car2049::engine_layers(int level, EngineLayer out[2]) {
    if (!setup49.loaded || level < 0 || level >= 8) {
        return false;
    }
    out[0] = setup49.engine_sounds[level][0];
    out[1] = setup49.engine_sounds[level][1];
    return true;
}
