// Three and four player races.
//
// Rush 2 keeps most race state per car (up to 8 cars, human players first), but a few things exist once per player
// or per view, sized for two: the player records, cameras, views and their viewports, and a few smaller arrays. Those
// move to bigger copies in free RDRAM (tools/players4/relocate.py generates the us.toml patches), or grow in place
// where only a small variable sat after them and that variable moved instead. This file copies the moved data at
// startup, fills in the records of players 3 and 4, and keeps the per-frame graphics buffers big enough for four
// views.
//
// Graphics buffers. Each frame's task (D_800D4060, two of them) has a 0xC980 byte buffer whose first 0x180 bytes hold
// the views' viewports, sky vertices, projections and root modelviews, laid out for two views. After them come three
// regions that grow up without bounds checks: a matrix pool (D_80022FE4) from +0x180, the display list (D_80022FD8)
// from +0x5900 and a second display list (D_80022FDC) from +0x9780. us.toml moves the per-view entries to a four-view
// layout (viewports +0x00, vertices +0x40, projections +0x80, modelviews +0x180, the shared modelview +0x280), and the
// buffers move to 256 KB blocks: the display list keeps its place at +0x5900 (the task setup, func_800B4214, assumes
// it), the second one starts at +0x18000 and the matrix pool at +0x28000.

#include <algorithm>
#include <atomic>
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <vector>

#include "recomp.h"
#include "rush2.h"
#include "rush2_hooks.h"
#include "players4.h"
#include "arrows.h"
#include "car2049.h"

namespace {
    // Moved arrays (generated by tools/players4/relocate.py cpp): old start, old end, new start. Their contents are
    // copied at startup; the rest of each new copy starts as zeros.
    struct Move {
        uint32_t old_start;
        uint32_t old_end;
        uint32_t new_start;
    };
    constexpr Move moves[] = {
        { 0x800C2190, 0x800C2268, 0x80240000 }, // string pointer table after the player records (frees room for records 2-3)
        { 0x800E7A50, 0x800E7A54, 0x802400E0 }, // camera variable inside the extended camera array
        { 0x800E7A58, 0x800E7AD8, 0x802400F0 }, // camera matrices, 0x40 per view
        { 0x80111888, 0x80111930, 0x802401F0 }, // player views, 0x54 per view
        { 0x8010C040, 0x8010C048, 0x80240340 }, // countdown sign objects, one per view
        { 0x800C100C, 0x800C1014, 0x80240350 }, // rumble timers, one f32 per player
        { 0x800D3F68, 0x800D3F78, 0x80240360 }, // rumble state, 8 bytes per player
        { 0x800E7B9C, 0x800E7B9E, 0x80240380 }, // car followed by each view
        { 0x800E7B38, 0x800E7B98, 0x80240390 }, // per-view camera state, 0x30 per view
        { 0x800E7AF0, 0x800E7AF8, 0x80240450 }, // camera f32 per view
        { 0x800E7BD0, 0x800E7BD2, 0x80240460 }, // camera byte per view
        { 0x800E7C20, 0x800E7C28, 0x80240470 }, // camera f32 per view
        { 0x800E7C38, 0x800E7C50, 0x80240480 }, // camera vector per view
        { 0x800E7CC0, 0x800E7CC8, 0x802404B0 }, // camera f32 per view
        { 0x800E7D10, 0x800E7D18, 0x802404C0 }, // camera f32 per view
        { 0x800E7D30, 0x800E7D38, 0x802404D0 }, // camera f32 per view
        { 0x800E7D48, 0x800E7D50, 0x802404E0 }, // camera f32 per view
        { 0x800E7B18, 0x800E7B30, 0x802404F0 }, // camera vector per view
        { 0x8010C0F0, 0x8010C108, 0x80240520 }, // camera vector per view
        { 0x8010C110, 0x8010C128, 0x80240550 }, // camera vector per view
        { 0x8010C130, 0x8010C138, 0x80240580 }, // camera f32 per view
        { 0x8010C148, 0x8010C150, 0x80240590 }, // camera f32 per view
        { 0x80110BE0, 0x80110BF8, 0x802405A0 }, // camera vector per view
        { 0x80112450, 0x80112454, 0x802405D0 }, // camera s16 per view
        { 0x80112458, 0x80112470, 0x802405E0 }, // camera vector per view
        { 0x80112478, 0x80112490, 0x80240610 }, // camera vector per view
        { 0x80112496, 0x8011249A, 0x80240640 }, // camera byte per view, stride 2
        { 0x80118A4C, 0x80118A50, 0x80240650 }, // camera s16 per view
        { 0x80118F78, 0x80118F7C, 0x80240660 }, // camera s16 per view
        { 0x80118FA0, 0x80118FA8, 0x80240670 }, // camera f32 per view
        { 0x80118FB0, 0x80118FB8, 0x80240680 }, // camera f32 per view
        { 0x800BFC74, 0x800BFC7C, 0x80240690 }, // camera f32 per view
        { 0x800BFC7C, 0x800BFC84, 0x802406A0 }, // camera f32 per view
        { 0x800FAE9C, 0x800FAEA0, 0x802406B0 }, // scene node drawn first in each view (s16, -1 for none)
        { 0x800D35E8, 0x800D35F0, 0x802406C0 }, // HUD f32 per player
        { 0x800D3A38, 0x800D3A40, 0x802406D0 }, // HUD f32 per player
        { 0x800D3AF0, 0x800D3AF8, 0x802406E0 }, // HUD f32 per player
        { 0x800D3968, 0x800D3978, 0x802406F0 }, // HUD 8 bytes per player
        { 0x800D39B8, 0x800D39C8, 0x80240710 }, // HUD 8 bytes per player
        { 0x8010C0D8, 0x8010C0E0, 0x80240730 }, // HUD f32 per player
        { 0x8010C3DC, 0x8010C3E0, 0x80240740 }, // HUD s16 per player (player 4 would land on the player count)
        { 0x80125AAA, 0x80125AAC, 0x80240750 }, // HUD byte per player
        { 0x80119888, 0x8011CA88, 0x802F0000 }, // HUD elements, 0x40 each (func_80081008)
        { 0x8011CA90, 0x8011CDB0, 0x802F6400 }, // free HUD element pointers (func_80060418)
        { 0x800F9558, 0x800FAE58, 0x802F6C00 }, // 2D widgets, 0x20 each (func_800541F8)
    };

    // Per-frame graphics buffers.
    constexpr uint32_t task_structs = 0x800D4060;
    constexpr int32_t task_buffer[2] = { 0x58, 0xD8 };
    constexpr uint32_t frame_blocks[2] = { 0x80250000, 0x80290000 };
    constexpr uint32_t frame_dl2_start = 0x18000;   // Second display list (D_80022FDC, grows up).
    constexpr uint32_t frame_pool_start = 0x28000;  // Matrix pool (D_80022FE4, grows up).
    constexpr uint32_t view_matrices = 0x80022FE0;
    constexpr uint32_t matrix_pool = 0x80022FE4;
    constexpr uint32_t dl_cursor = 0x80022FD8;
    constexpr uint32_t dl2_cursor = 0x80022FDC;

    // Player records.
    constexpr uint32_t records = 0x800C2140;
    constexpr uint32_t record_size = 0x28;
    constexpr int32_t record_car = 0x0;
    constexpr int32_t record_port = 0x1;
    constexpr int32_t record_buffer = 0x24; // The controller's buffer (0x8010D740 + port * 0x6C0) or a profile's.
    constexpr uint8_t no_port = 5;

    void copy_rdram(uint8_t* rdram, uint32_t dst, uint32_t src, uint32_t size) {
        for (uint32_t i = 0; i < size; i++) {
            MEM_B(0, (int32_t)(dst + i)) = MEM_B(0, (int32_t)(src + i));
        }
    }
}

extern "C" void race_fog_zone_setup_80081074(uint8_t* rdram, recomp_context* ctx);

namespace {
    constexpr uint32_t rumble_mask = 0x800D4E75; // Bit per port: rumble code drives its motor (func_80063E4C).

    // Players' controller ports, one byte per player (D_800BF314).
    constexpr uint32_t player_ports = 0x800BF314;
    constexpr uint32_t controller_buffers = 0x8010D740; // 0x6C0 per port.
    constexpr uint32_t controller_buffer_size = 0x6C0;

    // Views and cameras.
    constexpr uint32_t views = 0x802401F0; // Moved from 0x80111888.
    constexpr uint32_t view_size = 0x54;
    constexpr uint32_t cameras = 0x800E79D0; // 0x40 per view, position at +0x24.
    constexpr uint32_t camera_size = 0x40;
    constexpr int32_t camera_position = 0x24;
    constexpr uint32_t view_cars = 0x80240380; // Moved from 0x800E7B9C.
    constexpr uint32_t scene_list_heads = 0x802406B0; // s16 per view, moved from 0x800FAE9C.

    // View fields set by the game's fog setup (func_80054DCC, func_80081074).
    constexpr int32_t view_far = 0x38;
    constexpr int32_t view_fog_near = 0x4C;
    constexpr int32_t view_fog_far = 0x4E;
    constexpr int32_t view_fog_color = 0x50; // 4 bytes

    constexpr uint32_t game_state = 0x8010C0D0;

    // Per-car race state (0x354 each): +0xEA set once the car has finished (func_8008E8EC).
    constexpr uint32_t car_states = 0x801124A0;
    constexpr uint32_t car_state_size = 0x354;
    constexpr int32_t car_finished = 0xEA;

    int16_t player_count(uint8_t* rdram) {
        return MEM_H(0, (int32_t)rush2::players4::num_players);
    }

    // Sets up a view's fog for its camera's position, as the game does for views 0 and 1.
    void setup_view_fog(uint8_t* rdram, recomp_context* ctx, int view) {
        int32_t dst = (int32_t)(views + view * view_size);
        int32_t src = (int32_t)(views + 1 * view_size);
        for (int i = 0; i < 4; i++) {
            MEM_B(view_fog_color + i, dst) = MEM_B(view_fog_color + i, src);
        }
        recomp_context saved = *ctx;
        ctx->r4 = view;
        ctx->r5 = (int32_t)(cameras + view * camera_size + camera_position);
        race_fog_zone_setup_80081074(rdram, ctx);
        *ctx = saved;
    }
}

extern "C" void widgets_create_800604FC(uint8_t* rdram, recomp_context* ctx);

namespace {
    // Race HUD. func_800A06F8 builds the HUD's elements from a layout table (func_800604FC), each entry naming an
    // image, a position, an update callback and a parameter that, for per-player elements, holds the player: in its
    // low nibble or its second byte, by callback. The table has elements for players 1 and 2; players 3 and 4 get
    // copies of player 2's.
    constexpr uint32_t hud_layout = 0x800C2DB4;
    constexpr int hud_layout_count = 0x70;
    constexpr uint32_t hud_entry_size = 0x28;
    constexpr int32_t hud_entry_callback = 0x20;
    constexpr int32_t hud_entry_param = 0x24;
    constexpr uint32_t hud_elements = 0x8010C030;    // Head of the element list (+0x3C next).
    constexpr uint32_t hud_clone_table = 0x80248000; // Entries for players 3 and 4.
    constexpr int32_t element_widget = 0x34; // s16 widget slot, or -1
    constexpr int32_t element_callback = 0x28;
    constexpr int32_t element_param = 0x2C;
    constexpr int32_t element_next = 0x3C;
    constexpr int max_widgets = 400;
    // The element pool (moved by tools/players4/relocate.py, 400 entries: us.toml).
    constexpr int hud_pool_size = 400;
    constexpr uint32_t hud_element_array = 0x802F0000; // 0x40 each
    constexpr uint32_t hud_element_size = 0x40;
    constexpr uint32_t hud_element_pointers = 0x802F6400;
    constexpr int old_hud_pool_size = 200;
    constexpr uint32_t old_hud_element_array = 0x80119888;

    constexpr uint32_t nibble_player_callbacks[] = { 0x800B7B1C, 0x800B7E88, 0x800B9C44, 0x800B9CC0, 0x800B920C };
    constexpr uint32_t byte_player_callbacks[] = { 0x800BA2A8, 0x800B9754, 0x800B9978, 0x800BA608, 0x800B92F4,
                                                   0x800BA868, 0x800B8CC8, 0x800B5A90 };
    // The elements copied for players 3 and 4: all of player 2's (us.toml doubles the element and widget pools for
    // them): tachometer, speedometer, race and lap times, position, radar and the off-screen car arrows.
    constexpr uint32_t cloned_callbacks[] = { 0x800B7B1C, 0x800B7E88, 0x800BA2A8, 0x800B9754, 0x800B9978, 0x800BA608,
                                              0x800B92F4, 0x800BA868, 0x800B9C44, 0x800B9CC0, 0x800B920C, 0x800B8CC8 };

    // The player a HUD element (callback, parameter) belongs to, or -1 for shared elements.
    int element_player(uint32_t callback, uint32_t param) {
        for (uint32_t cb : nibble_player_callbacks) {
            if (cb == callback) {
                return (int)(param & 0xF);
            }
        }
        for (uint32_t cb : byte_player_callbacks) {
            if (cb == callback) {
                return (int)((param >> 8) & 0xF);
            }
        }
        return -1;
    }

    uint32_t with_player(uint32_t callback, uint32_t param, int player) {
        for (uint32_t cb : nibble_player_callbacks) {
            if (cb == callback) {
                return (param & ~0xFu) | (uint32_t)player;
            }
        }
        return (param & ~0xF00u) | ((uint32_t)player << 8);
    }

    constexpr int max_clones = 128;
    uint32_t built_list = 0;
    int8_t widget_players[max_widgets];
    rush2::players4::HudRole widget_roles[max_widgets];
    bool widget_lap_time[max_widgets];

    rush2::players4::HudRole element_role(uint32_t callback) {
        using rush2::players4::HudRole;
        switch (callback) {
            case 0x800B9754: // race time
            case 0x800B9978: // lap time
                return HudRole::Time;
            case 0x800BA2A8:
                return HudRole::Speed;
            case 0x800B7B1C: // tachometer's dim background (translucent), under the speedometer (shown in manual)
            case 0x800B7E88: // tachometer's lit part and its tip
                return HudRole::Tach;
            case 0x800B92F4: // gear (shown in manual)
                return HudRole::Gear;
            case 0x800BA608:
                return HudRole::Position;
            case 0x800B920C: // radar
            case 0x800B8CC8: // its car dots
                return HudRole::Radar;
            case 0x800B5A90: // place once finished (the finish overlay)
                return HudRole::Banner;
            case 0x800B9C44: // deaths count
            case 0x800B9CC0: // its skull
                return HudRole::Deaths;
            case 0x800B94C0: // time left (shared)
                return HudRole::TimeLeft;
            case 0x800B8188: // track map (shared)
                return HudRole::Map;
            default:
                return HudRole::Other;
        }
    }
}

namespace {
    // Notes the player and role of each widget of an element list.
    void tag_widgets(uint8_t* rdram, uint32_t head) {
        for (uint32_t e = head; e != 0; e = (uint32_t)MEM_W(element_next, (int32_t)e)) {
            int slot = MEM_H(element_widget, (int32_t)e);
            uint32_t callback = (uint32_t)MEM_W(element_callback, (int32_t)e);
            if (slot >= 0 && slot < max_widgets) {
                widget_players[slot] = (int8_t)element_player(callback, (uint32_t)MEM_W(element_param, (int32_t)e));
                widget_roles[slot] = element_role(callback);
                widget_lap_time[slot] = callback == 0x800B9978;
            }
        }
    }

    // Copies a layout table's entries for player 2 (element_player 1) for players 3 and 4 into the table at "to";
    // returns how many.
    int clone_player_entries(uint8_t* rdram, uint32_t table, int entries, uint32_t to, int players, int max_count) {
        int count = 0;
        for (int i = 0; i < entries; i++) {
            int32_t entry = (int32_t)(table + i * hud_entry_size);
            uint32_t callback = (uint32_t)MEM_W(hud_entry_callback, entry);
            uint32_t param = (uint32_t)MEM_W(hud_entry_param, entry);
            if (element_player(callback, param) != 1) {
                continue;
            }
            for (int player = 2; player < players && count < max_count; player++) {
                int32_t copy = (int32_t)(to + count * hud_entry_size);
                copy_rdram(rdram, (uint32_t)copy, (uint32_t)entry, hud_entry_size);
                MEM_W(hud_entry_param, copy) = (int32_t)with_player(callback, param, player);
                count++;
            }
        }
        return count;
    }

    // Builds the elements of a layout table and appends them to an element list.
    void append_elements(uint8_t* rdram, recomp_context* ctx, uint32_t head, uint32_t table, int count) {
        if (count == 0) {
            return;
        }
        recomp_context saved = *ctx;
        ctx->r4 = 0;
        ctx->r5 = 0;
        ctx->r6 = (int32_t)table;
        ctx->r7 = count;
        widgets_create_800604FC(rdram, ctx);
        uint32_t added = (uint32_t)ctx->r2;
        *ctx = saved;
        uint32_t last = head;
        while ((uint32_t)MEM_W(element_next, (int32_t)last) != 0) {
            last = (uint32_t)MEM_W(element_next, (int32_t)last);
        }
        MEM_W(element_next, (int32_t)last) = (int32_t)added;
    }

    // The race's finish overlay (func_800A0FB4: each player's place once finished, from 0x800BF328, 7 entries).
    constexpr uint32_t finish_layout = 0x800BF328;
    constexpr int finish_layout_count = 7;
    constexpr uint32_t finish_clone_table = 0x8024A000; // Entries for players 3 and 4.
}

namespace rush2::players4 {
    void finish_overlay_built(uint8_t* rdram, recomp_context* ctx, uint32_t head) {
        if (head == 0) {
            return;
        }
        int players = player_count(rdram);
        if (players > 2) {
            int count = clone_player_entries(rdram, finish_layout, finish_layout_count, finish_clone_table, players, 6);
            append_elements(rdram, ctx, head, finish_clone_table, count);
        }
        tag_widgets(rdram, head);
    }

    int32_t record(int player) {
        return (int32_t)(records + player * record_size);
    }

    void hud_built(uint8_t* rdram, recomp_context* ctx) {
        uint32_t head = (uint32_t)MEM_W(0, (int32_t)hud_elements);
        if (head == 0 || head == built_list) {
            return;
        }
        int players = player_count(rdram);
        if (players > 2) {
            // Copies of player 2's entries for players 3 and 4.
            int count = 0;
            for (int i = 0; i < hud_layout_count && count < max_clones; i++) {
                uint32_t entry = hud_layout + i * hud_entry_size;
                uint32_t callback = (uint32_t)MEM_W(hud_entry_callback, (int32_t)entry);
                if (std::find(std::begin(cloned_callbacks), std::end(cloned_callbacks), callback) != std::end(cloned_callbacks)) {
                    count += clone_player_entries(rdram, entry, 1, hud_clone_table + count * hud_entry_size, players,
                                                  max_clones - count);
                }
            }
            append_elements(rdram, ctx, head, hud_clone_table, count);
        }

        // Each widget's player and role, from its element's callback and parameter (set when it was built).
        for (int slot = 0; slot < max_widgets; slot++) {
            widget_players[slot] = -1;
            widget_roles[slot] = rush2::players4::HudRole::Other;
            widget_lap_time[slot] = false;
        }
        tag_widgets(rdram, head);
        built_list = head;
    }

    int hud_widget_player(int slot) {
        return slot >= 0 && slot < max_widgets ? widget_players[slot] : -1;
    }

    bool hud_widget_lap_time(int slot) {
        return slot >= 0 && slot < max_widgets && widget_lap_time[slot];
    }

    HudRole hud_widget_role(int slot) {
        return slot >= 0 && slot < max_widgets ? widget_roles[slot] : HudRole::Other;
    }

    void frame(uint8_t* rdram) {
        MEM_H(0, (int32_t)clamped_players) = (int16_t)std::min<int>(player_count(rdram), 2);
        // Views 2 and 3 draw the scene lists of views 0 and 1.
        for (int view = 2; view < max_players; view++) {
            MEM_H(view * 2, (int32_t)scene_list_heads) = MEM_H((view & 1) * 2, (int32_t)scene_list_heads);
        }
    }
}

extern "C" void player_join_init_car_80080524(uint8_t* rdram, recomp_context* ctx);
extern "C" void car_set_pedals_80076854(uint8_t* rdram, recomp_context* ctx);
extern "C" void player_join_init_car_dynamics_800806A4(uint8_t* rdram, recomp_context* ctx);
extern "C" void input_steering_from_stick_80076694(uint8_t* rdram, recomp_context* ctx);
extern "C" void input_set_port_state_80093DC0(uint8_t* rdram, recomp_context* ctx);
extern "C" void menu_play_sound_80064908(uint8_t* rdram, recomp_context* ctx);
extern "C" void carselect_build_list_803B81F0(uint8_t* rdram, recomp_context* ctx);

namespace {
    // Joining. Player 2 joins by pressing START on a free controller in the menus (func_80093E08, which fills record 2
    // from the controller's state and sets the counts of players and views to 2). The menus are built for two
    // players, so players 3 and 4 join the same way but the counts stay at 2 until the race starts (race_start);
    // records 3 and 4 having a port marks them as joined.
    constexpr uint32_t cars = 0x800F5470; // 0x81C per car
    constexpr uint32_t car_size = 0x81C;
    constexpr uint32_t port_pressed = 0x8010C458;  // u16 per port, buttons pressed this frame
    constexpr uint32_t port_state_4 = 0x8010C208;  // u16 per port -> record +4
    constexpr uint32_t port_state_6 = 0x8010C478;  // u16 per port -> record +6
    constexpr uint32_t port_state_8 = 0x8010C3C8;  // 2 bytes per port -> record +8
    constexpr uint32_t port_state_a = 0x8010C138;  // 2 bytes per port -> record +0xA
    constexpr uint32_t port_profiles = 0x801174F0; // s16 per port: the Controller Pak profile chosen, or -1/-2
    constexpr uint32_t pak_profiles = 0x8004B1E0;  // 4 paks of 0x2200 bytes, 5 profiles of 0x6C0 each from +0x40
    constexpr uint16_t start_button = 0x1000;
    constexpr int sound_join = 0x3F;
    constexpr int sound_back = 0x32;
    constexpr int ports = 4;
    constexpr uint32_t controller_map = 0x8010C150; // s8 per port: the controller read for it, -1 for none
    constexpr uint32_t hint_text = 0x8024F100; // The join hint's string (free RDRAM, include/players4.h).
    constexpr int hint_style = 0xA;            // Text style the menus print with (func_800737E4).
    constexpr uint32_t menu_screen = 0x800E7BC4; // s16: the front end screen up (func_800AE0D4 runs its step).
    constexpr int16_t screen_select_player = 1;  // func_803B4D88

    // Game states (D_8010C0D0) of the menus where players may join: the front end and the track select.
    bool joining_allowed(int32_t state) {
        return state == 0 || state == 1;
    }

    uint8_t port_of(uint8_t* rdram, int player) {
        return (uint8_t)MEM_BU(record_port, rush2::players4::record(player));
    }

    void call(uint8_t* rdram, recomp_context* ctx, void (*func)(uint8_t*, recomp_context*), int32_t a0 = 0,
              int32_t a1 = 0, int32_t a2 = 0, int32_t a3 = 0) {
        recomp_context saved = *ctx;
        ctx->r4 = a0;
        ctx->r5 = a1;
        ctx->r6 = a2;
        ctx->r7 = a3;
        func(rdram, ctx);
        *ctx = saved;
    }

    // Player 3 or 4 joins on a port, as func_80093E08 does for player 2.
    void join(uint8_t* rdram, recomp_context* ctx, int player, int port) {
        int32_t rec = rush2::players4::record(player);
        int32_t car = (int32_t)(cars + player * car_size);
        MEM_B(player, (int32_t)player_ports) = (int8_t)port;
        MEM_B(record_port, rec) = (int8_t)port;
        MEM_H(0x2, rec) = MEM_H(port * 2, (int32_t)port_pressed);
        MEM_H(0x4, rec) = MEM_H(port * 2, (int32_t)port_state_4);
        MEM_H(0x6, rec) = MEM_H(port * 2, (int32_t)port_state_6);
        MEM_B(0x8, rec) = MEM_B(port * 2, (int32_t)port_state_8);
        MEM_B(0x9, rec) = MEM_B(port * 2 + 1, (int32_t)port_state_8);
        MEM_B(0xA, rec) = MEM_B(port * 2, (int32_t)port_state_a);
        MEM_B(0xB, rec) = MEM_B(port * 2 + 1, (int32_t)port_state_a);
        call(rdram, ctx, player_join_init_car_80080524, car, rec, (int32_t)(port_pressed + port * 2), (int32_t)(port_state_8 + port * 2));
        {
            // func_80076854 takes the car in $s0 and the record in $s1.
            recomp_context saved = *ctx;
            ctx->r16 = car;
            ctx->r17 = rec;
            car_set_pedals_80076854(rdram, ctx);
            *ctx = saved;
        }
        call(rdram, ctx, player_join_init_car_dynamics_800806A4, car);
        call(rdram, ctx, input_steering_from_stick_80076694, rec, car);

        // Players 3 and 4 skip the Select Player screen: they race with the controller's own record, or the profile
        // already chosen on that controller (as func_800A6B58 picks them).
        int profile = MEM_H(port * 2, (int32_t)port_profiles);
        if (profile < 0) {
            MEM_H(port * 2, (int32_t)port_profiles) = -1;
            MEM_W(record_buffer, rec) = (int32_t)(controller_buffers + port * controller_buffer_size);
        }
        else {
            MEM_W(record_buffer, rec) =
                (int32_t)(pak_profiles + (profile / 5) * 0x2200 + (profile % 5) * controller_buffer_size + 0x40);
        }
        call(rdram, ctx, input_set_port_state_80093DC0, port, 1);
        call(rdram, ctx, menu_play_sound_80064908, sound_join);
    }

    void leave(uint8_t* rdram, int player) {
        int32_t rec = rush2::players4::record(player);
        MEM_B(record_port, rec) = (int8_t)no_port;
        MEM_W(record_buffer, rec) = 0;
    }

    // AI-agent test aid, not in the menu: RUSH2_TEST_PLAYERS=3 or 4 fills the empty player slots up to that count with
    // idle players (see update_joining), to try the 3 and 4 player screens without extra controllers.
    int test_players_from_env() {
        const char* v = std::getenv("RUSH2_TEST_PLAYERS");
        int n = v != nullptr ? std::atoi(v) : 0;
        return (n == 3 || n == 4) ? n : 0;
    }
    const int test_players = test_players_from_env();

    // Each menu frame: a START press on a free controller adds player 3 or 4 once player 2 is in; players 3 and 4
    // leave with player 2. Test players (RUSH2_TEST_PLAYERS) join by themselves on ports with no controller.
    void update_joining(uint8_t* rdram, recomp_context* ctx) {
        if (!joining_allowed(MEM_W(0, (int32_t)game_state))) {
            return;
        }
        if (port_of(rdram, 1) == no_port || player_count(rdram) < 2) {
            for (int player = 2; player < rush2::players4::max_players; player++) {
                if (port_of(rdram, player) != no_port) {
                    leave(rdram, player);
                }
            }
            return;
        }
        int player = 2;
        while (player < rush2::players4::max_players && port_of(rdram, player) != no_port) {
            player++;
        }
        if (player == rush2::players4::max_players) {
            return;
        }
        bool fill = player < test_players;
        for (int port = 0; port < ports; port++) {
            bool used = false;
            for (int p = 0; p < player; p++) {
                used = used || port_of(rdram, p) == port;
            }
            if (used) {
                continue;
            }
            if (fill ? !rush2::input::is_port_connected(port) : (MEM_HU(port * 2, (int32_t)port_pressed) & start_button) != 0) {
                join(rdram, ctx, player, port);
                return;
            }
        }
    }

    // Car select. The screen has two players' panels, so with 3 or 4 players it runs twice: once everyone in the first
    // round has chosen, players 3 and 4 take players 1 and 2's places (records, ports and per-player car table rows
    // swapped) and the screen starts over for them; once they have chosen, everything is swapped back and the race
    // starts. Backing out of the second round returns to the first.
    int car_round = 0; // 1 while players 3 and 4 choose.

    // Rush 2's race car table (9 bytes per car slot: +1 type, +2..+5 colors and stripe). The second round's screen
    // setup rewrites slots 0 and 1 (players 1 and 2) with defaults (type 0 = the pickup truck), so round one's picks
    // are kept here and put back once round two is done.
    constexpr uint32_t race_car_table = 0x800D9C10;
    constexpr int race_car_entry_size = 9;
    int8_t saved_car_entries[2 * race_car_entry_size] = {};

    void save_car_entries(uint8_t* rdram) {
        for (int i = 0; i < 2 * race_car_entry_size; i++) {
            saved_car_entries[i] = MEM_B(i, (int32_t)race_car_table);
        }
    }

    void restore_car_entries(uint8_t* rdram) {
        for (int i = 0; i < 2 * race_car_entry_size; i++) {
            MEM_B(i, (int32_t)race_car_table) = saved_car_entries[i];
        }
    }

    void swap_players(uint8_t* rdram, int a, int b) {
        int32_t ra = rush2::players4::record(a);
        int32_t rb = rush2::players4::record(b);
        for (int32_t i = 0; i < (int32_t)record_size; i++) {
            int8_t x = MEM_B(i, ra);
            MEM_B(i, ra) = MEM_B(i, rb);
            MEM_B(i, rb) = x;
        }
        int8_t x = MEM_B(a, (int32_t)player_ports);
        MEM_B(a, (int32_t)player_ports) = MEM_B(b, (int32_t)player_ports);
        MEM_B(b, (int32_t)player_ports) = x;
        rush2::car2049::swap_player_rows(rdram, a, b);
    }

    void swap_rounds(uint8_t* rdram, int total) {
        swap_players(rdram, 0, 2);
        if (total > 3) {
            swap_players(rdram, 1, 3);
        }
    }
}

extern "C" void text_center_x_800734AC(uint8_t* rdram, recomp_context* ctx);
extern "C" void text_print_string_800734E0(uint8_t* rdram, recomp_context* ctx);
extern "C" void text_select_style_800737E4(uint8_t* rdram, recomp_context* ctx);

namespace rush2::players4 {
    // On the Select Player screen, where player 2 joins, once player 2 is in: which of players 3 and 4 can still press
    // START. Joining also works on Start Game and the track select, but player 2 stays in after backing out of Select
    // Player to Start Game, whose one player layout made the hint look stuck there.
    void draw_join_hint(uint8_t* rdram, recomp_context* ctx) {
        char text[40];
        int32_t center_x = 160;
        int32_t y = 190; // Above the screen's bottom bars.
        if (car_round != 0 && MEM_W(0, (int32_t)game_state) == 2 && player_count(rdram) == 1) {
            // Player 3 alone in the car select's second round: its one player layout has no label, so it gets one at
            // the right end of the title bar.
            snprintf(text, sizeof(text), "PLAYER 3");
            center_x = 262;
            y = 24;
        }
        else {
            if (MEM_W(0, (int32_t)game_state) != 0 || MEM_H(0, (int32_t)menu_screen) != screen_select_player ||
                port_of(rdram, 1) == no_port || player_count(rdram) < 2) {
                return;
            }
            int next = joined_players(rdram);
            if (next >= max_players) {
                return;
            }
            snprintf(text, sizeof(text), "PLAYER %d PRESS START TO JOIN", next + 1);
        }
        for (int i = 0; i <= (int)strlen(text); i++) {
            MEM_B(i, (int32_t)hint_text) = (int8_t)text[i];
        }
        call(rdram, ctx, text_select_style_800737E4, hint_style);
        recomp_context saved = *ctx;
        ctx->r4 = (int32_t)hint_text;
        ctx->r5 = center_x;
        text_center_x_800734AC(rdram, ctx);
        int32_t x = (int16_t)ctx->r2;
        *ctx = saved;
        call(rdram, ctx, text_print_string_800734E0, x, y, (int32_t)hint_text);
    }

    int joined_players(uint8_t* rdram) {
        if (port_of(rdram, 1) == no_port) {
            return std::min<int>(player_count(rdram), 2);
        }
        int count = 2;
        while (count < max_players && port_of(rdram, count) != no_port) {
            count++;
        }
        return count;
    }
}

extern "C" {

// func_803B9478 (car select) once every player has chosen, before the race is started: true to stay on the screen.
int rush2_players4_cars_chosen(uint8_t* rdram, recomp_context* ctx) {
    int total = rush2::players4::joined_players(rdram);
    if (total <= 2) {
        car_round = 0;
        return false;
    }
    swap_rounds(rdram, total);
    if (car_round == 0) {
        MEM_H(0, (int32_t)rush2::players4::num_players) = (int16_t)(total - 2);
        save_car_entries(rdram);
        car_round = 1;
        call(rdram, ctx, menu_play_sound_80064908, sound_join);
        call(rdram, ctx, carselect_build_list_803B81F0, 0); // Ends the screen; it sets itself up again next frame.
        return true;
    }
    MEM_H(0, (int32_t)rush2::players4::num_players) = 2;
    restore_car_entries(rdram);
    car_round = 0;
    return false;
}

// func_803BC048 (car select text), after a panel's "PLAYER %d" label is formatted at $sp + 0x6C: the second round's
// panels are players 3 and 4.
void rush2_players4_car_label(uint8_t* rdram, recomp_context* ctx) {
    if (car_round == 0) {
        return;
    }
    int32_t text = (int32_t)ctx->r29 + 0x6C;
    for (int i = 0; i < 32 && MEM_B(i, text) != 0; i++) {
        char c = (char)MEM_B(i, text);
        if (c >= '1' && c <= '2' && MEM_B(i + 1, text) == 0) {
            MEM_B(i, text) = (int8_t)(c + 2);
        }
    }
}

// func_803B9478 (car select) when a player backs out: true to stay on the screen.
int rush2_players4_cars_back(uint8_t* rdram, recomp_context* ctx) {
    if (car_round == 0) {
        return false;
    }
    swap_rounds(rdram, rush2::players4::joined_players(rdram));
    MEM_H(0, (int32_t)rush2::players4::num_players) = 2;
    car_round = 0;
    call(rdram, ctx, menu_play_sound_80064908, sound_back);
    call(rdram, ctx, carselect_build_list_803B81F0, 0);
    return true;
}

}

extern "C" {

// func_800B4EB0, after the frame tasks are set up at startup. Copies the moved arrays to their new homes, sets up the
// records of players 3 and 4, and points the frame tasks at the bigger graphics buffers.
void rush2_players4_init(uint8_t* rdram, recomp_context* ctx) {
    for (const Move& m : moves) {
        copy_rdram(rdram, m.new_start, m.old_start, m.old_end - m.old_start);
    }
    // The free element pointers point into the element array, which moved and grew: point them at the new one.
    for (int i = 0; i < hud_pool_size; i++) {
        int32_t at = (int32_t)(hud_element_pointers + i * 4);
        uint32_t element = (uint32_t)MEM_W(0, at);
        if (i < old_hud_pool_size && element >= old_hud_element_array &&
            element < old_hud_element_array + old_hud_pool_size * hud_element_size) {
            MEM_W(0, at) = (int32_t)(hud_element_array + (element - old_hud_element_array));
        }
        else if (i >= old_hud_pool_size) {
            MEM_W(0, at) = (int32_t)(hud_element_array + i * hud_element_size);
        }
    }

    // Records 3 and 4 take the place of the string table that moved; they start as copies of record 2 (its button
    // map and settings) with their own cars and no controller.
    for (int player = 2; player < rush2::players4::max_players; player++) {
        int32_t rec = rush2::players4::record(player);
        copy_rdram(rdram, (uint32_t)rec, (uint32_t)rush2::players4::record(1), record_size);
        MEM_B(record_car, rec) = (int8_t)player;
        MEM_B(record_port, rec) = (int8_t)no_port;
        MEM_W(record_buffer, rec) = 0;
    }

    // Views 2 and 3 follow cars 2 and 3.
    MEM_B(2, (int32_t)view_cars) = 2;
    MEM_B(3, (int32_t)view_cars) = 3;

    for (int i = 0; i < 2; i++) {
        MEM_W(task_buffer[i], (int32_t)task_structs) = (int32_t)frame_blocks[i];
    }
    rush2::players4::frame(rdram);
}

// func_803AA92C (each menu screen's per-frame step), on the game's main thread.
void rush2_players4_menu(uint8_t* rdram, recomp_context* ctx) {
    // Back in the menus, which are built for two players, after a race with more.
    if (joining_allowed(MEM_W(0, (int32_t)game_state)) && player_count(rdram) > 2) {
        MEM_H(0, (int32_t)rush2::players4::num_players) = 2;
        MEM_H(0, (int32_t)rush2::players4::num_views) = 2;
    }
    update_joining(rdram, ctx);
}

// func_800A6B58 (START on the title screen), once it has found the port that pressed START ($s0, and $s1 = port * 2):
// player 1 is the first port with a controller or the keyboard in the Players tab, whichever device pressed START.
// Otherwise, after a race, START from the device set up as player 2 or 3 (pressed to get through the results) made it
// player 1, and it then did nothing on "PRESS START TO JOIN".
void rush2_players4_title_port(uint8_t* rdram, recomp_context* ctx) {
    for (int port = 0; port < ports; port++) {
        if (rush2::input::port_has_device(port)) {
            ctx->r16 = port;
            ctx->r17 = port * 2;
            return;
        }
    }
}

// func_800AE670 (the game's state machine), each frame.
void rush2_players4_state(uint8_t* rdram, recomp_context* ctx) {
    int32_t state = MEM_W(0, (int32_t)game_state);
    if (state == 4 && player_count(rdram) > 2) {
        MEM_H(0, (int32_t)rush2::players4::num_players) = 2;
        MEM_H(0, (int32_t)rush2::players4::num_views) = 2;
    }
}

// func_800A0FB4, before it draws the dark box behind player 1's or 2's place once finished: split side by side or in
// quadrants, the boxes are left out (they're placed for views stacked top and bottom, and players 3 and 4 have none).
int rush2_players4_skip_finish_box(uint8_t* rdram, recomp_context* ctx) {
    return rush2::splitscreen::is_side_by_side(rdram) || rush2::splitscreen::quadrant_views(rdram) != 0;
}

// func_800AE670, once players 1 and 2 have finished the race: whether players 3 and 4 have too.
int rush2_players4_all_finished(uint8_t* rdram, recomp_context* ctx) {
    for (int player = 2; player < player_count(rdram); player++) {
        int car = MEM_BU(record_car, rush2::players4::record(player));
        if (MEM_B(car_finished, (int32_t)(car_states + car * car_state_size)) == 0) {
            return 0;
        }
    }
    return 1;
}

// func_800AE670, as a race is set up (before the cars are given to the players, func_800A580C): players 3 and 4 who
// have joined take part.
void rush2_players4_race_start(uint8_t* rdram, recomp_context* ctx) {
    int total = rush2::players4::joined_players(rdram);
    if (player_count(rdram) == 2 && total > 2) {
        MEM_H(0, (int32_t)rush2::players4::num_players) = (int16_t)total;
        MEM_H(0, (int32_t)rush2::players4::num_views) = (int16_t)total;
    }
    rush2::players4::frame(rdram);
}

// func_800A5ADC, after the fog of views 0 and 1 is set up (func_80081074). Sets up views 2 and 3.
void rush2_players4_race_views(uint8_t* rdram, recomp_context* ctx) {
    for (int view = 2; view < MEM_H(0, (int32_t)rush2::players4::num_views); view++) {
        setup_view_fog(rdram, ctx, view);
    }
}

// func_800AE670, after the per-frame fog update of views 0 and 1 (in game states 3 and 10).
void rush2_players4_frame_views(uint8_t* rdram, recomp_context* ctx) {
    int32_t state = MEM_W(0, (int32_t)game_state);
    if (state != 3 && state != 0xA) {
        return;
    }
    for (int view = 2; view < MEM_H(0, (int32_t)rush2::players4::num_views); view++) {
        setup_view_fog(rdram, ctx, view);
    }
}

// func_800B45B4 (frame setup), after it sets the frame's graphics buffer pointers from the task. Moves the matrix pool
// and the second display list to their places in the bigger buffer.
void rush2_players4_frame_buffers(uint8_t* rdram, recomp_context* ctx) {
    uint32_t base = (uint32_t)MEM_W(0, (int32_t)view_matrices);
    MEM_W(0, (int32_t)matrix_pool) = (int32_t)(base + frame_pool_start);
    MEM_W(0, (int32_t)dl2_cursor) = (int32_t)(base + frame_dl2_start);

    // The controller thread (func_80076DE0) reads only the ports its map (D_8010C150, -1 = none) had a controller on
    // when it last scanned: at boot (where the runtime's scan reports only one port present) and when the Controller
    // Pak code asks it to (D_80023060, not set from here: that would break the pak code's exchange with it). A port
    // whose controller is assigned or found later was never read, so the map follows the ports' controllers (and the
    // ports an input script presses on, which test players may also sit on).
    for (int port = 0; port < ports; port++) {
        bool read = rush2::input::is_port_connected(port) || rush2::input::is_port_scripted(port);
        MEM_B(port, (int32_t)controller_map) = (int8_t)(read ? port : -1);
        // The pak thread only registers a port with the rumble code (mask D_800D4E75) if a controller was there when
        // it last scanned, so a controller assigned to port 3 or 4 later never rumbled. Those ports report a Rumble Pak
        // (src/pak.cpp), so the rumble update's own osMotorInit finds it once the bit is set.
        if (read && port >= 2) {
            MEM_B(0, (int32_t)rumble_mask) = (int8_t)(MEM_BU(0, (int32_t)rumble_mask) | (1 << port));
        }
    }
}

// func_8007B518 (draws a scene graph level for a view, $a2), after the offset of the view's link in a node ($s0 =
// view * 2): views 2 and 3 follow the links of views 0 and 1.
void rush2_players4_list_offset(uint8_t* rdram, recomp_context* ctx) {
    ctx->r16 = ((uint32_t)ctx->r6 & 1) * 2;
}

// func_8007C624, after the view's bit is made to test a world polygon's view mask ($t7 = 1 << view, the view at
// $sp+0x180): views 2 and 3 also draw the polygons of views 0 and 1. $fp = the polygon. The arrows over the other
// players' cars (src/arrows.cpp) each belong to one view of the four.
void rush2_players4_poly_mask(uint8_t* rdram, recomp_context* ctx) {
    if (rush2::arrows::single_view((uint32_t)ctx->r30)) {
        return;
    }
    int32_t view = MEM_W(0x180, ctx->r29);
    ctx->r15 = (uint32_t)ctx->r15 | (1u << (view & 1));
}

}
